### ISSUE TITLE
Nested Aggregation

### ISSUE THREAD

**Issue by npatmaja** [danpaz/bodybuilder#10]
Hi, I'm looking a way to create a [nested aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-nested-aggregation.html) query, but I can't find how to do it yet. Am I missing something when I'm reading the documentation or currently it is not supported yet?

**Comment by danpaz** [comment]
Nested aggregation is currently not supported. Sounds like that's not clear from the documentation so I'll add a note in the readme for now. Do you have an idea of how to implement arbitrarily nested aggregations?
