### ISSUE TITLE
Q: Is bodybuilder working with ElasticSearch 5.x?

### ISSUE THREAD

**Issue by jgbarah** [danpaz/bodybuilder#105]
I see in the documentation that it works with 1.x and 2.x. What about 5.x? Any experience about problems / no problems with it?

**Comment by dlumbrer** [comment]
@danpaz said in #94 that the DSL did not change significantly from 2.x to 5.x. Bodybuilder should support it using `'v2'` into `.build`

**Comment by danpaz** [comment]
@dlumbrer is right, and note that in the [next version of bodybuilder](https://github.com/danpaz/bodybuilder/releases/tag/v2.0.0-beta.1) the `'v2'` argument will no longer be needed as it is the new default.
