### ISSUE TITLE
Sort by nested document property

### ISSUE THREAD

**Issue by antonsamper** [danpaz/bodybuilder#107]
This might be a similar issue to the Geo Distance Sort (https://github.com/danpaz/bodybuilder/issues/58) but i was wondering if there is currently a way to sort by a property on a nested document.

Lets say you wanted to retrieve a list of documents and order them based on when the most recent transaction date was. The output for the sort property should be something like this:
```
sort: {
    'transactions.date': {
        'order': 'desc',
        'nested_path': 'transactions'
    }
}
```

Is this possible at the moment?

**Comment by danpaz** [comment]
Not possible it looks like. I'm a little wrapped up in getting #103 merged and released, but this should be pretty straightforward to fix if anyone wants to give it a try. In particular it looks like [`sortMerge`](https://github.com/danpaz/bodybuilder/blob/master/src/utils.js#L70) picked out the `order` keys and ignores all other keys. Perhaps it'd just work to use `Object.assign` there.

Thanks for raising the issue @antonsamper

**Comment by antonsamper** [comment]
@danpaz i can give it a try. Is it better to work off `master` or the `prerelease-bodybuilder-2` branch?

**Comment by danpaz** [comment]
Either branch is fine, but if you work off of prerelease-bodybuilder-2 the diff might be slightly cleaner after #103. We can always retarget your PR to master if #103 lands before your PR. Thanks!
