### ISSUE TITLE
Q: Generic way to build nested aggs of different types (terms, histograms, ranges.. etc)

### ISSUE THREAD

**Issue by dlumbrer** [danpaz/bodybuilder#111]
Hi,

I want to build 'unlimited' nested aggs regardless of the type they are (terms, histogram, date_histogram, etc). I saw in #89 that it can be possible, but its only works with type "Terms". 

Is there any way (generic) to do it?

For example, I can have an array with differents types of aggs that i want to nest:
```js
var statements = [{ 
  "aggregationType":"terms", 
  "aggregationField":"name" 
}, { 
  "aggregationType":"date_histogram", 
  "aggregationField":"field1" ,
  "interval": "1M"
}, { 
  "aggregationType":"histogram", 
  "aggregationField":"field2" 
  "interval" : "2000"
}]
```

Thanks

**Comment by danpaz** [comment]
Could you do something similar like:

```js
var statements = [{ 
  "aggregationType":"terms", 
  "aggregationField":"name" 
}, { 
  "aggregationType":"date_histogram", 
  "aggregationField":"field1" ,
  "aggregationOptions": {"interval" : "1M"}
}, { 
  "aggregationType":"histogram", 
  "aggregationField":"field2" 
  "aggregationOptions": {"interval" : "2000"}
}]

statements.forEach(function(s) {
  agg.aggregation(s.aggregationsType, s.aggregationField, s.aggregationOptions)
})
```
I haven't tested it though.
Btw this is more of a javascript question not specific to bodybuilder, and you may get better answers from posting it on e.g. stackoverflow. Hope this helps!
