### ISSUE TITLE
function_score disappeared?

### ISSUE THREAD

**Issue by mikeholmesuk** [danpaz/bodybuilder#112]
hiya,

I'm already using the library, but I noticed that a few things broke with the 2.0.0 release (well done on getting to a 2.0.0 release by the way). The main thing that has stung me is that there no longer appears to be support for `function_score`? I checked through the migration document and I tried to find instances of `functionScore`/`function_score`/ `functionScoreQuery` (as per the `1.x.x` version of the library) but I can't find it. Has it been removed? If so is there a replacement for it?

**Comment by danpaz** [comment]
Thanks for the issue @mikeholmesuk. Version 2.0.0 of bodybuilder should support all queries including `function_score` by default; instead of using templates for specific queries the api is now more generic. Can you post the query you had working in 1.x.x and we can see how to build it in 2.0.0? 

This may be a candidate for more explanation in the migrations doc.

**Comment by mikeholmesuk** [comment]
Hey @danpaz, thanks for getting back to me so quickly. 

Example of a working query is as follows (this is part of a wider query, but works for demoing):

```    builder.query('function_score', [
        {exp: {
            'profile.go_live_date': {
                origin: 'now',
                offset: '14d',
                scale: '7d'
            },
        }}
    ], { boost: 0.5 });```

Which would generate somehitng like this: ```   "query": {
      "bool": {
         "filter": {
            "term": {
               "profile.status": "approved"
            }
         },
         "must": {
            "function_score": {
               "functions": [
                  {
                     "exp": {
                        "profile.go_live_date": {
                           "origin": "now",
                           "offset": "14d",
                           "scale": "7d"
                        }
                     }
                  }
               ],
               "boost": 0.5
            }
         }
      }
   }```

Have you an example of using v2.0.0 with `function_score`? The docs aren't particularly helpful with regards to examples so in the previous example I used the tests for documentation. There don't seem to be any for `function_score` anymore (unless I'm missing something)?

**Comment by mikeholmesuk** [comment]
Ok, have worked it out. Above seems to be resolved by adjusting it slightly:
```
    builder.query('function_score', { functions: [
        {exp: {
            'profile.go_live_date': {
                origin: 'now',
                offset: '14d',
                scale: '14d'
            },
        }}
    ], boost: 0.5 });
```

Happy to close this issue @danpaz. Separately, would you be happy to accept a couple of PRs if I update the docs with some examples?

**Comment by danpaz** [comment]
For sure documentation PRs are my fave! 👍
