### ISSUE TITLE
Is there a way to 'plugin' features?

### ISSUE THREAD

**Issue by mcampster** [danpaz/bodybuilder#115]
We are using bodybuilder to build complex aggregations in our application. What I would like to do is abstract the various parts of the query into reusable aggregations and filters, so we don't have to repeat ourselves.

For example, I would like a filter that restricts to 'open orders'. Rather than have to specify this explicitly each time, I would like to just say 'bodybuilder().openOrders();

Further still, I want to do the same with aggregations...

bodybuilder().openOrders().byProduct();
bodybuilder().openOrders().byUser();

The fluent syntax, along with the concept of nested aggregations/filters etc, is making this complicated (for me at least). Is there a way of doing?

I can 'monkey patch' the return type of bodybuilder(), but this only gives me top level support, and doesn't append my fluent API to the nested instances of bodybuilder.

**Comment by danpaz** [comment]
I don't know if this lib was built for the way you're interested in using it. But one idea is you might be able to make use of "private" apis like `getQuery`, `getFilter`, `getAggregations`. These return built  clauses that you can keep a reference to. For example:

```js
var f = bodybuilder()
        .query('term', 'user', 'kimchy')
        .query('term', 'user', 'herald')
f.getQuery()
```

I'll close this issue for now as I don't think there's an action to take or PR to make, but happy to keep discussing here.

**Comment by mcampster** [comment]
Using your example, you've got the same 'code' twice. Wouldn't it be nice if I could write it like this...

```
var f = bodybuilder()
        .queryUser('kimchy')
        .queryUser('herald')
```

If bodybuilder had some way for the user to register these functions they could then be used in the fluent interface. 

The reason I cannot make this work is due to nested aggregations and filters... 

`Object.assign({}, queryBuilder(), filterBuilder(), aggregationBuilder()).`

If we could assign a custom user object here, as well as the defaults, we could achieve this.
