### ISSUE TITLE
not found post_filter support, without using rawOption

### ISSUE THREAD

**Issue by kodekracker** [danpaz/bodybuilder#117]
https://www.elastic.co/guide/en/elasticsearch/guide/current/_post_filter.html

**Comment by danpaz** [comment]
I feel like `rawOption` is the right way to accomplish this. Maybe the tricky part is constructing the filter in a "bodybuilder" way, in which case you could consider using the private api `getFilter` like this:

```js
var f = bodybuilder().filter('term', 'color', 'green').getFilter()
bodybuilder().rawOption('post_filter', f).build()
```

Let me know if that doesn't work for you.

**Comment by demisx** [comment]
Would be nice if a post filter could be attached simple than this. At least with `.rawOption`. Current way is pretty verbose.

```ts
...
.rawOption('post_filter', (b) => {
    b.filter('term', {color: 'green'})
    return b
  })
.build()
```
