### ISSUE TITLE
is any way to build has_child with should option

### ISSUE THREAD

**Issue by chiragob** [danpaz/bodybuilder#120]
<pre>
{
  "query":
  {
    "bool":
    {
      "should": [
       {   
      	"has_child": {
		    "inner_hits":{},
		    "type": "emp",
		    "query": {
			    "match": {
			      "name": "xyz"
			    }
			  }
		    }
          },
          {
            "bool":
            {
              "must":
              [
                  {
                    "match" : { "name" : "xyz" }
                  },
                  {
                    "match" : { "_type" : "emps" }
                  }
              ],
              "must_not": [
                {
                  "has_child": {
                    "type": "emp",
                    "query": {
                      "exists":
                            {
                              "field": "name"
                            }
                    }
                  }
                }
              ]
            }
          }
        ]
      }
    }
}
</pre>

**Comment by chiragob** [comment]
i tried below build but not working
<pre>
bodybuilder()
  .orQuery('has_child',bodybuilder()
                 .rawOption("inner_hits", {})
                 .rawOption("type", "emp")
                 .query('match', 'name', 'xyz')
                 .build())
  .orQuery('match',bodybuilder()
        .query('match','name','xyz') 
        .query('match','_type','emps')
        .notQuery('has_child', 
                      bodybuilder()
                      .rawOption("type", "emp")
                      .query('exists', 'field', 'name')
                      .build()
                 )
        .build())
.build()
</pre>

**Comment by danpaz** [comment]
It's a bit quirky but this is how I'd write it: 

```js
var inner = bodybuilder()
	.query('match', 'name', 'xyz')	
	.query('match', '_type', 'emps')	
	.notQuery('has_child', {type: 'emp'}, (q) => {
		return q.query('exists', 'field', 'name')
	})
	.build()

bodybuilder()
	.orQuery('bool', inner.query.bool)
        .orQuery('has_child', {inner_hits: {}, type: 'emp'}, (q) => {
		return q.query('match', 'name', 'xyz')	
	})
	.build()
```

Something to watch out for: the order of the `orQuery`s matters here, it doesn't work if these are switched, which isn't ideal. I think that's because of how the `bool` clauses are being merged. Let me know is this isn't working for you.

**Comment by chiragob** [comment]
thanks
