### ISSUE TITLE
Issues With Filter Clause Inside Bool Query

### ISSUE THREAD

**Issue by IdanWo** [danpaz/bodybuilder#121]
[As far a I can see,](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-filter-context.html) since ElasticSearch 2.x and above - there shouldn't be any difference between the structure of "Must" and "Filter" clauses inside bool queries. However, there is a difference in bodybuilder. I have added an explanation below. 

I believe the issues are leftovers from previous bodybuilder versions supporting ElasticSearch 1.x. What do you think?

## MUST ##
**Single must:**
```
bodybuilder()
		.query('term','user','Idan')
  		.build()
```
result as expected by bodybuilder:
```
{
  "query": {
    "term": {
      "user": "Idan"
    }
  }
}
```
**Multiple musts:**
```
bodybuilder()
		.query('term','user','Idan')
		.query('term','level','INFO')
  		.build()
```

result as expected by bodybuilder. 
An ordinary array. 
```
{
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "user": "Idan"
          }
        },
        {
          "term": {
            "level": "INFO"
          }
        }
      ]
    }
  }
}
```
## FILTER ##
**Single filter:**
```
bodybuilder()
		.filter('term','user','Idan')
  		.build()
```
Result as expected by bodybuilder. 
It might look unnecessary to wrap the clause with bool since it is only a single clause, however this way will make sure no score will be calculated ("Filter context is in effect whenever a query clause is passed to a filter parameter, such as the filter or must_not parameters in the bool query, the filter parameter in the constant_score query, or the filter aggregation").
```
{
  "query": {
    "bool": {
      "filter": {
        "term": {
          "user": "Idan"
        }
      }
    }
  }
}
```
**Multiple filters:**
```
bodybuilder()
   	        .filter('term','user','Idan')
		.filter('term','level','INFO')
  		.build()
```
Unexpected result by bodybuilder. 
Why wrapping the clauses with bool and must, instead of an ordinary array?
```
{
  "query": {
    "bool": {
      "filter": {
        "bool": {
          "must": [
            {
              "term": {
                "user": "Idan"
              }
            },
            {
              "term": {
                "level": "INFO"
              }
            }
          ]
        }
      }
    }
  }
}
```

**Comment by danpaz** [comment]
So to clarify, bodybuilder output is:
```json
{
  "query": {
    "bool": {
      "filter": {
        "bool": {
          "must": [
            {
              "term": {
                "user": "Idan"
              }
            },
            {
              "term": {
                "level": "INFO"
              }
            }
          ]
        }
      }
    }
  }
}
```

and you are expecting:
```json
{
  "query": {
    "bool": {
      "filter": [
            {
              "term": {
                "user": "Idan"
              }
            },
            {
              "term": {
                "level": "INFO"
              }
            }
          ]
    }
  }
}
```

So the `bool.must` inside the filter is not required. But the code is written with the more generic case in mind, where a filter can have nested `must_not`, `should`, so updating the code to simplify this output would complicate the logic. 

Does this extra nesting cause an issue with the resulting query as interpreted in elasticsearch?

**Comment by sudo-suhas** [comment]
Filter clause queries are not scored so you can expect better performance, depending on the query. There are caching implications as well.

I have been working on an [alternate library](/sudo-suhas/elastic-builder) for building elasticsearch DSL, heavily inspired by [elastic.js](/fullscale/elastic.js) and bodybuilder.
Code snippet:
```js
const bob = require('elastic-builder');

const boolQry = bob.boolQuery()
    .filter(bob.termQuery('user', 'Idan'))
    .filter(bob.termQuery('level', 'INFO'))
    .toJSON(); // build DSL

// JSON.stringify(boolQry, null, 2);
{
  "bool": {
    "filter": [
      { "term": { "user": "Idan" } },
      { "term": { "level": "INFO" } }
    ]
  }
}
```
I hope it is okay if I mention it here. Will EDIT and remove content if required.

**Comment by danpaz** [comment]
Cool! Good luck and I'll close this issue since there's no action to take, feel free to reopen if there's more to do here.

**Comment by cperryk** [comment]
Hey @danpaz — Thanks for this lib. It's fantastic. On this issue, I don't understand the case for turning multiple `filter` calls turn into a `must` array as opposed to a `filter` array. Can't additional queries be nested within a `filter` array just as they can in a `must` array? ElasticSearch's documentation emphasizes repeatedly that `filter` queries are more performant because they do not score documents.

[Elasticsearch: The Definitive Guide](https://www.elastic.co/guide/en/elasticsearch/guide/master/_queries_and_filters.html):

> Filtering queries are simple checks for set inclusion/exclusion, which make them very fast to compute. There are various optimizations that can be leveraged when at least one of your filtering query is "sparse" (few matching documents), and frequently used non-scoring queries can be cached in memory for faster access.
> 
> In contrast, scoring queries have to not only find matching documents, but also calculate how relevant each document is, which typically makes them heavier than their non-scoring counterparts. Also, query results are not cacheable.

Happy to help out with this by submitting a PR, but let me know what you think first.

**Comment by cperryk** [comment]
To elaborate, consider this:
```
bodybuilder()
  .filter('term', 'foo')
  .filter('term', 'bar')
  .build()
```

Which produces this:
```
{
  "query": {
    "bool": {
      "filter": {
        "bool": {
          "must": [
            {
              "term": {
                "field": "foo"
              }
            },
            {
              "term": {
                "field": "bar"
              }
            }
          ]
        }
      }
    }
  }
}
```
I'm not wondering why that JS turns two filter calls into a separate `bool` query -- that makes sense if we need to chain it with other clauses at that first level -- I'm wondering why that _new_ `bool` query uses a `must` instead of a `filter` clause. Why doesn't the above JS produce this instead?
```
{
  "query": {
    "bool": {
      "filter": {
        "bool": {
          "filter": [
            {
              "term": {
                "field": "foo"
              }
            },
            {
              "term": {
                "field": "bar"
              }
            }
          ]
        }
      }
    }
  }
}
```

**Comment by IdanWo** [comment]
I believe this issue should be re-opened. In my system no scoring is used, so I would like to ignore it completely.

**Comment by Gia90** [comment]
The worst thing is that the 2 queries have a different meaning.
It means that they **return different results** and currently there's no way to get the filters array instead of a bool/must in the final built query if using this library.

**Comment by sudo-suhas** [comment]
@Gia90 I am not 100% sure about this but the search results wouldn't be different right? If I am wrong about this, I am curious to know why the results are different.

**Comment by Gia90** [comment]
@sudo-suhas I meant that the two queries perform 2 different kind of searches, one is a match and the other one is an actual filtering without score calculation.
Sorry if I didn't express myself clearly.

**Comment by sudo-suhas** [comment]
Yes, I had pointed that out as well. See https://github.com/danpaz/bodybuilder/issues/121#comment-296454548

**Comment by johannes-scharlach** [comment]
I understand the elasticsearch docs so that the query is executed in filter context once filter context is initiated https://www.elastic.co/guide/en/elasticsearch/reference/current/query-filter-context.html

In other words: once you're in filter context, you can't execute a a query in query context anymore.

Do you have any example or docs that show that those two are different? In that case is be happy to reopen and address this asap

**Comment by sudo-suhas** [comment]
The difference is in the work elasticsearch does for a query which would have scores calculated as opposed to a filter query which only helps to determine if a document should be part of the response or not.

**Comment by johannes-scharlach** [comment]
> The difference is in the work elasticsearch does

If the results are exactly the same, then the work can be optimised by elasticsearch (and I would assume that's already happening)

> users might want to have fine grained control over which queries are part of the scoring

It's a `must` in _filter context_, so it should have no effect on scoring. If you can point to an example where the scoring is actually different, I'd be happy to address this suggestion.

**Comment by derek-miller** [comment]
I might have missed something somewhere but is there a way to not apply the filter in a _filter context_ so I can sort by __score_?

**Comment by johannes-scharlach** [comment]
@derek-miller if you want the score to be taken into account, use `.query` and `.orQuery`. `.filter` and `.orFilter` are for cases where you _don't_ want scoring to have any influence.
