### ISSUE TITLE
How to generate filtered aggregation using generic aggregation builder in v2

### ISSUE THREAD

**Issue by vipulbpl** [danpaz/bodybuilder#125]
If I want to generate a filtered aggregation using the aggregation builder, how should I go about it since the parameters it accepts are - 

aggregation(type: (string | Object), field: string, options: [Object], name: [string], nest: [Function], args: ...any):

Confused regarding where should I mention the filters to be applied on this aggregation?
Thanks 
@danpaz

**Comment by gophry** [comment]
@vipulbpl 

```
bodybuilder()
.agg('avg','price','category_avg')
.agg('filter','','brand',(a)=>{
  return (
    a.filter('term','brand.raw_lowercase','apple'),
    a.agg('avg','price','brand_avg')
  )
}).build()
```
GENERATES THE FOLLOWING:
```
{
  "aggs": {
    "category_avg": {
      "avg": {
        "field": "price"
      }
    },
    "brand": {
      "filter": {
        "term": {
          "brand.raw_lowercase": "apple"
        }
      },
      "aggs": {
        "brand_avg": {
          "avg": {
            "field": "price"
          }
        }
      }
    }
  }
}
```
Hope it helps.

**Comment by danpaz** [comment]
@gophry I love it when people from the community jump in to answer questions, keep it up! :+1:. 

@vipulbpl I'll close this assuming this comment solves your issue
