### ISSUE TITLE
Update Sort documentation

### ISSUE THREAD

**Issue by diegoprd** [danpaz/bodybuilder#127]
Sort documentation section is only showing the `field: direction` approach.
But the library is actually accepting many other options such as Object and Array of sortObjects.

I needed to do a `_geo_distance` sort and I did it, but it would help others to know that those kind of things are possible by updating the documentation.

I am more than happy to do it myself @danpaz, but not sure what is the procedure, may I ask you how is the process you are following to update the documentation? is it just manually updating the `docs/index.html` file or there is any automated process ?

best

**Comment by danpaz** [comment]
There is an automated process using jsdoc :)

Just add to the jsdoc in the source and run `npm run build:docs` to generate the html docs. Thanks!

**Comment by johannes-scharlach** [comment]
@diegoprd the documentation in question can be changed here https://github.com/danpaz/bodybuilder/blob/master/src/index.js#L64-L70

If your offer to improve the docs still stands, I'd be more than happy to see a MR for that!
