### ISSUE TITLE
Issue while generating or into and filter ES query

### ISSUE THREAD

**Issue by Gautam17** [danpaz/bodybuilder#128]
![image](https://cloud.githubusercontent.com/assets/14542950/25019627/eb2329f2-20a8-11e7-8dec-6ba2897a606a.png)

In Given image, I am trying to build query where must[] will contain bool.should[] (similar to given in following JSON ) but `bodyBuilder` is considering that both `must` and `should` are on the same level.

Hi, can anyone please help me to build the following query using bodyBuilder module?

```
{
  "_source":["shape.id","carat"],
  "query": {
    "bool": {
      "filter": {
        "bool": {
          "must": [
            {
              "bool": {
                "should": [
                  {
                    "range": {
                      "carat": {
                        "gt": 1,
                        "lt": 1.5
                      }
                    }
                  },
                  {
                    "range": {
                      "carat": {
                        "gt": 5,
                        "lt": 10
                      }
                    }
                  }
                ]
              }
            },
            {
              "terms": {
                "shape.id": [
                  1 
                ]
              }
            }
          ]
        }
      }
    }
  }
}
```

**Comment by gophry** [comment]
```
bodybuilder()
.orFilter('range','price',{'gt':100,'lt':200})
.orFilter('range','price',{'gt':600,'lt':900})
.filter('terms','brand',['sony','samsung'])
.build()
```

The query structure does not map exactly but the output with my data just matches perfectly. Modify accordingly to your needs it should work.

**Comment by gophry** [comment]
`
var inner = bodybuilder()
.orFilter('range','price',{'gt':100,'lt':200})
.orFilter('range','price',{'gt':600,'lt':900})
.build()


var body = bodybuilder()
.andFilter('bool')
.filter('terms','brand',['sony','samsung'])
.build()

body.query.bool.filter.bool.must.push(inner.query.bool.filter)
body
`
@Gautam17 This is exact replica of the query you are looking for. Both first and second query give same output. If you can check and confirm if it works in your environment.

**Comment by Gautam17** [comment]
@gophry  thank you for your comment,
Is it possible to create a complex query by using bodybuilder() object?
because if I will go with ```body.query.bool.filter.bool.must.push(inner.query.bool.filter)``` I have to add conditions like must is undefined or not

**Comment by gophry** [comment]
@Gautam17 

as mentioned in the first comment: 
I had a similar requirement and this works. The complex queries do not exactly look many a times the way we nest but has worked all times perfectly. Rather i have replaced 50% of my queries with this in last 2 days.

Try this:
```
bodybuilder()
.rawOption('fields',['price','brand])
.orFilter('range','price',{'gt':100,'lt':200})
.orFilter('range','price',{'gt':600,'lt':900})
.filter('terms','brand',['sony','samsung'])
.build()
```

**Comment by danpaz** [comment]
I can't confirm in my environment but I think @gophry is right that the first simpler query will give the same result as the other more complex query. If you confirm that you _do_ need something more like the complex case because the elasticsearch results are different, let us know and we can explore alternatives to `body.query.bool.filter.bool.must.push(inner.query.bool.filter)`, which I agree is not ideal.

**Comment by Gautam17** [comment]
using npm version 2.2.0 its working fine
![bodybuilder js org-2017-07-10-10-25-15](https://user-images.githubusercontent.com/14542950/28003280-2b4691ae-655a-11e7-9f4e-c58b05c25ed9.png)

**Comment by Gautam17** [comment]
@danpaz sorry for late response, I have complex requirement like search entity is having 52 paramters with 10+ possible values 
E.g param-1 shape, possible values are round, heart, square and so on

**Comment by johannes-scharlach** [comment]
@Gautam17 we've actually updated bodybuilder and version 2.2 should be able to fulfil your wishes, because now you can generate a nested filter

```js
bodybuilder()
  .query('bool', b => b
     .orFilter('range','price',{'gt':100,'lt':200})
     .orFilter('range','price',{'gt':600,'lt':900})
  )
  .build()  
```

I think this is what you wanted
