### ISSUE TITLE
Multi match creates invalid query

### ISSUE THREAD

**Issue by ilongin** [danpaz/bodybuilder#129]
This example: 
```
bodybuilder()
        .query('multi_match', [ "info.name^3", "info.main_url^2" ], 'this is a test')
		.filter('term', 'user', 'kimchy')
        .build()
```

creates this query json: 
```
{
  "query": {
    "bool": {
      "filter": {
        "term": {
          "user": "kimchy"
        }
      },
      "must": {
        "multi_match": {
          "info.name^3,info.main_url^2": "this is a test"
        }
      }
    }
  }
}
```
which is invalid query (tested with ES validate method ). I think problem is that multi_match expect 'fields' and 'query' argument and here it just creates query that is similar to normal match query.

**Comment by gophry** [comment]
@ilongin 
wherever i face this issue i pass it as a object. But needs something better i feel.
bodybuilder()
.query('multi_match',{
  "query":    ""this is a test"",
  "fields": [ "info.name^3", "info.main_url^2" ]
})
.filter('term', 'user', 'kimchy')
.build()

**Comment by gophry** [comment]
There should be a better method it seems:

i have worked with some small cheats.
```

bodybuilder()
.query('multi_match','field',[ "info.name^3", "info.main_url^2" ],{'query':'this is text'})
.filter('term', 'user', 'kimchy')
.build()
```


Output as follows:
```

{
  "query": {
    "bool": {
      "filter": {
        "term": {
          "user": "kimchy"
        }
      },
      "must": {
        "multi_match": {
          "field": [
            "info.name^3",
            "info.main_url^2"
          ],
          "query": "this is text"
        }
      }
    }
  }
}
```

**Comment by gophry** [comment]
v1 documentation mentions it.
https://github.com/danpaz/bodybuilder/blob/a9bcdc57370b9ffd2f833120d166b469382c5d49/docs/API.md

v2 does not have it.

**Comment by caioflores** [comment]
Thanks @gophry for this solution, @ilongin my approach if it helps:

    // Expected elastic query  
    query: {
        bool: {
          must: [
            {
              multi_match: {
                query: userQuery,
                fields: ['Field1^1000', 'Field2^3', 'Field3^2', 'Field4'],
                fuzziness: 5,
                prefix_length: 0,
              },
            },
          ],
        },
      },

My object:

    const query = bodybuilder();
    query.query(
        'multi_match',
        'fields',
        ['Field1^1000', 'Field2^3', 'Field3^2', 'Field4'],
        { query: userQuery,
          fuzziness: 5,
          prefix_length: 0,
    });

**Comment by johannes-scharlach** [comment]
The idea with bodybuilder v2 is that for complex queries like multi_match or query_string, you only specify an options object, like this:

```js
bodybuilder()
  .query(
    'multi_match',
    {
      query: 'hello',
      fuzziness: 5,
      prefix_length: 0,
      fields: ['Field1^1000', 'Field2^3', 'Field3^2', 'Field4']
    }
  )
  .build()
```

**Comment by rossvz** [comment]
Just ran into this - would be great to have this documented in the docs somewhere!
