### ISSUE TITLE
queryMinimumShouldMatch doesn't apply to body

### ISSUE THREAD

**Issue by reidblomquist** [danpaz/bodybuilder#130]
Steps to reproduce:

Build a body with orQueries as well as must queries; add queryMinimumShouldMatch - no param set on bool.

Expected behavior: the param is on the bool query.

Have manually intercepted the body and added this param - works as expected.

**Comment by danpaz** [comment]
Thanks for the bug report. Could you post the query you used to reproduce this?

**Comment by reidblomquist** [comment]
const body = bodybuilder();

      body.query('term', 'some_key', 'some_value');

      searchTerms.forEach((term) => {
        body.orQuery('prefix', 'attributes.some_attr', term);
        if (idRegex.test(term)) {
          body.orQuery('term', 'attributes.some_other_attr', term.replace(idReplace, ''));
        }
      });

      body.queryMinimumShouldMatch(1);

      setPasted(false);

      searchAction(body.build())
        .then((res) => {
          // ...do some stuff
        });
    }
  }

**Comment by reidblomquist** [comment]
Current workaround:

```
  const body = bodybuilder();

  body.query('term', 'some_key', 'some_value');

  searchTerms.forEach((term) => {
    body.orQuery('prefix', 'attributes.some_attr', term);
    if (idRegex.test(term)) {
      body.orQuery('term', 'attributes.some_other_attr', term.replace(idReplace, ''));
    }
  });

  const bugBody = body.build();

  bugBody.query.bool.minimum_should_match = 1;

  setPasted(false);

  searchAction(bugBody)
    .then((res) => {
      // ...do some stuff
    });
}
```

**Comment by reidblomquist** [comment]
@danpaz is that what you were looking for? If you point me in the right direction I might be able to whip up a PR to fix behavior; we're using this pretty heavily in our app and would be happy to contribute.

**Comment by danpaz** [comment]
A PR to fix would be great, haven't had time to look at this closely yet. Thanks!

**Comment by reidblomquist** [comment]
Hmm, for some reason I can't get the tests to fail on my branch from master. Will dig in more and see what could be causing it on our app/look at versions and test specific releases perhaps.

commit with test changes: https://github.com/reidblomquist/bodybuilder/commit/4826ef006f3e807501312045b1f52c0c6ff4478f

**Comment by johannes-scharlach** [comment]
A few things around minimum should match have changed lately, so if this is not reproducible, it may have been fixed already. Hence I'll close this issue for now.

@reidblomquist a MR with the additional test cases would be great anyways!

**Comment by aaronkrolik** [comment]
This still appears broken in the current build. Setting queryMinimumShouldMatch has no affect on the query object.

**Comment by danpaz** [comment]
@aaronkrolik can you share the query you are working with? 

Internally [the library checks](https://github.com/danpaz/bodybuilder/blob/master/src/utils.js#L92-L93) if the minimum_should_match is valid to include by checking if there are at least two `or` clauses. I suspect your query is hitting this condition. There is also an option to add an override parameter `.queryMinimumShouldMatch(2, true)` as a workaround if the internal check isn't working the way you expect.
