### ISSUE TITLE
Query Construction Help - orFilter - Complex filter based on multiple attributes

### ISSUE THREAD

**Issue by tvskart** [danpaz/bodybuilder#132]
Hi guys. Firstly, really love this library. 

Question:
I need help constructing a complex filter query. Initially, the query filters for docs that  have either one of the tags. Broke it down this way so that the complicated version is hopefully easier to understand.

code1: 
`bodybuilder().orFilter("terms", "tags",  ["Popular"].orFilter("terms", "tags",  ["Emerging"];`

query1: 
```
"query": {
    "bool": {
	"filter": {
		"bool": {
			"should": [
  			    {
  				"terms": {
  				   "tags": ["Popular"]
  			         }
  			    },
  			    {
  				"terms": {
  				   "tags": ["Emerging"]
  				}
  			    }, ...
```

Now, the query gets complex as it is supposed to filter based on an additional attribute along with the tags. i.e. we filter docs based on combo of tags and brands values.
Expected query: 

query2:
```
{
	"query": {
		"bool": {
			"filter": {
				"bool": {
					"should": [
						{"bool": {
							"must": [
								{"terms": {"tags": ["Popular"]}},
								{"terms": {"brands": ["A", "B"]}}
							]
						}},
						{"bool": {
							"must": [
								{"term": {"tags": ["Emerging"]}},
								{"terms": {"brands": ["C"]}}
							]
						}},
						{"bool": {
							"must": [
								{"terms": {"tags": ["Rumor"]}},
								{"terms": {"companies": ["A", "C", "D"]}}
							]
						}}
					]
				}
			}
		}
	},
```

I tried a code which works like this ->
code2:
`q.filter("terms", "tags", ["Popular"]);`
`q.filter("terms", "brands", ["A", "B"]);`
`q = q.build();`
`query.orFilter("bool", "must", q.query.bool.must);`
`// ... repeat for other combinations and add to query.`

However, this code doesn't work as expected.. I already feel like 
`orFilter("bool", "must", q.query.bool.must);` is hacky on my part. Maybe there is an obvious way I'm missing. Appreciate any help. Thanks.

**Comment by johannes-scharlach** [comment]
In fact that's not yet supported as far as I know, but I needed similar functionality and proposed some changes to allow for this in https://github.com/danpaz/bodybuilder/pull/134

**Comment by johannes-scharlach** [comment]
@tvskart The mentioned MR has been merged and a new version of bodybuilder was published – Does it work for you now?

**Comment by tvskart** [comment]
@johannes-scharlach ,  awesome contribution! This greatly reduces the complexity of our implementation so far, and makes it much more maintainable!

Previously used to do something "hacky" like so -> 

```
               query = bodybuilder();
               query.getQuery().bool = query.getQuery().bool || {};
                if (value.length > 1) {
                    query.getQuery().bool.should = query.getQuery().bool.should || [];
                    value.map(a => {
                        const innerQuery = bodybuilder().query("term", "tags", a.tag);
                        if (a.brands.length > 0) {
                            innerQuery.query("terms", "brands", a.brands);
                        }
                        query.getQuery().bool.should.push(innerQuery.getQuery());
                    });
                } else if (value.length === 1) {
                    let a = value[0];
                    query.getQuery().bool.must = query.getQuery().bool.must || [];
                    const innerQuery = bodybuilder().query("term", "tags", a.tag);
                    if (a.brands.length > 0) {
                        innerQuery.query("terms", "brands", a.brands);
                    }
                    query.getQuery().bool.must.push(innerQuery.getQuery());
                }
```
Now we can execute a simpler, more readable query similar to what @danpaz outlined - https://github.com/danpaz/bodybuilder/pull/134#issuecomment-304554099  

Thank u so much.
