### ISSUE TITLE
Multi field filter using range

### ISSUE THREAD

**Issue by punit07** [danpaz/bodybuilder#135]
Hi, I am looking to "filter" multiple fields for a range i.e. less than 50.

I have currently this ... (which looks so verbose)

```
                   .orFilter('range', 'atarcloud', {
                        lte: atar_radio_value
                    })
                    .orFilter('range', 'atarwaurnponds', {
                        lte: atar_radio_value
                    })
                    .orFilter('range', 'atarwarrnambool', {
                        lte: atar_radio_value
                    })
                    .orFilter('range', 'atarburwood', {
                        lte: atar_radio_value
                    })
                    .orFilter('range', 'atarwaterfront', {
                        lte: atar_radio_value
                    })
```

I saw [this ](https://github.com/danpaz/bodybuilder/blob/master/docs/API.md#multimatchquery) but the documentation is so poor. Hardly any examples on how to use a feature. 

Can someone please help ?

Thanks

**Comment by johannes-scharlach** [comment]
I don't think what you want is possible with any elasticsearch query. The only range query I'm aware of is this one: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-range-query.html

so what you're doing is exactly right. What you can do with bodybuilder though:

```js
const builder = require('bodybuilder')()

['atarcloud', 'atarwaurnponds', 'atarwarrnambool', 'atarburwood', 'atarwaterfront'].forEach(field => {
  builder.orFilter('range', field, { lte: atar_radio_value })
})
```
which is much shorter than your version :)
