### ISSUE TITLE
Nested aggregation with path param

### ISSUE THREAD

**Issue by schermannj** [danpaz/bodybuilder#136]
Suppose we have next doc:
`{
    ...

    "product" : {
        "properties" : {
            "resellers" : { 
                "type" : "nested",
                "properties" : {
                    "name" : { "type" : "text" },
                    "price" : { "type" : "double" }
                }
            }
        }
    }
}`

Is there a way to built next aggregation query:
`{

    "query" : {
        "match" : { "name" : "led tv" }
    },
    "aggs" : {
        "resellers" : {
            "nested" : {
                "path" : "resellers"
            },
            "aggs" : {
                "min_price" : { "min" : { "field" : "resellers.price" } }
            }
        }
    }
}`

**Comment by schermannj** [comment]
So... I've found a way, but it looks a bit strange, here it is: 
`
const nestedResellersAgg = agg => agg.aggregation('min', 'resellers.price', 'min_price');
bb.aggregation('nested', undefined, 'resellers', { path: 'resellers' }, nestedPetsAgg)
`

Something like this, but it would be great to do it in some other way ;)

**Comment by sudo-suhas** [comment]
A bit late but here you go:
```js
bodybuilder()
    .query('match', 'name', 'led tv')
    .aggregation(
        'nested', 
        { path: 'resellers' }, 
        'resellers',
        agg => agg.aggregation('min', 'resellers.price', 'min_price')
    )
    .build()
```

**Comment by johannes-scharlach** [comment]
Closing this as a solution has been provided.

@sudo-suhas with https://github.com/danpaz/bodybuilder/pull/147 we should start mentioning all contributors to this project. I see you answering a lot of important questions, so feel free to add yourself by running `npm run add -- sudo-suhas question`

**Comment by sudo-suhas** [comment]
@johannes-scharlach Thank you for suggesting this. However, for adding myself, I'd have to wait for #147, fork, clone, install packages, run the command and then make a PR. I am fine with just answering questions once in a while without adding myself to contributors 😁. However, if you could run the command in my stead in #147 itself, I'd be really grateful.

**Comment by johannes-scharlach** [comment]
@sudo-suhas Didn't think you'd be so fast to respond ;) Done!

**Comment by sudo-suhas** [comment]
Thanks!
