### ISSUE TITLE
Angular 2

### ISSUE THREAD

**Issue by islimane** [danpaz/bodybuilder#137]
Hi,

How can I use bodybuilder on an Angular2 project? I've installed the npm package but I can't figure out how to use it.

Thanks.

**Comment by haoliangyu** [comment]
You need to write a [type declaration file](http://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html) to use this library in TypeScript because such file doesn't exist at [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) yet.

**Comment by johannes-scharlach** [comment]
Would be very happy to see such a type declaration file! :)

I'll close this issue for now, but would be super happy to see an MR about it.

**Comment by jacobwgillespie** [comment]
I just opened PR #174 that adds a TypeScript type declaration file.

**Comment by jackrvaughan** [comment]
Still don't get how this is supposed to work in angular2+ ? 

I'm doing this right now:
```
declare function require(name: string);
var bodybuilder = require('bodybuilder');
```
