### ISSUE TITLE
minimum_should_match only supports numeric input

### ISSUE THREAD

**Issue by ferronrsmith** [danpaz/bodybuilder#138]
```javascript
  if (
    unwrapped.minimum_should_match &&
    unwrapped.minimum_should_match <= filters.or.length
  ) {
    cleaned.minimum_should_match = unwrapped.minimum_should_match
}
```

Can also be (-/+) percentage or (multi) combinations

https://www.elastic.co/guide/en/elasticsearch/reference/master/query-dsl-minimum-should-match.html

Think this should be the same as Elasticsearch.  No magic, let the user control the field and set it once it exists.

```javascript
  if (
    unwrapped.minimum_should_match
  ) {
    cleaned.minimum_should_match = unwrapped.minimum_should_match
}
```

**Comment by ferronrsmith** [comment]
submitted PR : https://github.com/danpaz/bodybuilder/pull/139

**Comment by ferronrsmith** [comment]
@danpaz can you look at this and merge it in ?

**Comment by johannes-scharlach** [comment]
You're absolutely right! I'd say the current version is a bug and I'm glad you fixed it :)

**Comment by johannes-scharlach** [comment]
🎉 @danpaz has released your fix 🙌 

I'll close this issue for now
