### ISSUE TITLE
docs for topHitsAggregation

### ISSUE THREAD

**Issue by eamonnfaherty** [danpaz/bodybuilder#141]
Hi,

Thanks for this awesome library!

I am having an issue where I cannot see any docs for topHitsAggregation that show how to execute this type of request.

I would expect it to work in the same way as the normal aggregation but it seems to fail:
 bodybuilder()
            .filter('term', 'SomeField', "Success")
            .filter('term', 'SomeOtherField', true)
            .topHitsAggregation()
            .build()

**Comment by ferronrsmith** [comment]
Think you're referring to the v1 release. The documentation doesn't show v1, at least not anymore.
You can use raw git on the latest v1 tag to view the docs.

https://cdn.rawgit.com/danpaz/bodybuilder/v1.25.0/docs/index.html#AggregationstopHitsAggregation

**Comment by ferronrsmith** [comment]
v1 example

For v1 you can simply check the tests.

https://github.com/danpaz/bodybuilder/blob/v1.25.0/test/aggregations/top-hits-aggregation.js

v2 example

```javascript
bodybuilder().size(0)
	.aggregation('top_hits', null, 'results', {
		"sort": [
          {
            "balance": {
              "order": "desc"
            }
          }
        ],
        "_source": {
          "includes": [
            "age"
          ]
        },
        "size": 3
	})
	.build()
```

**Comment by sudo-suhas** [comment]
I am guessing you are not looking to build a v1 object. Following is an the bodybuilder syntax for the [`top_hits` example](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-top-hits-aggregation.html) from elasticsearch reference guide:
```js
bodybuilder()
    .aggregation(
        // agg type
        'terms',
        // field
        'type',
        // additional opts
        { size: 3 },
        // agg name
        'top_tags',
        // nested aggregation
        agg =>
            agg.aggregation(
                'top_hits',
                {
                    sort: [{ date: { order: 'desc' } }],
                    _source: { includes: ['date', 'price'] },
                    size: 1
                },
                'top_sales_hits'
            )
    )
    .build();
```

**Comment by johannes-scharlach** [comment]
I believe the question here was sufficiently answered
