### ISSUE TITLE
cumulative sum use field rather then buckets_path

### ISSUE THREAD

**Issue by unioah** [danpaz/bodybuilder#149]
in cumulative aggregation, the default key should be buckets_path rather then field

**Comment by ferronrsmith** [comment]
This is something that we definitely need to support. We only support metric aggregations at this time. 
If it's something you need urgently, take a look at [elastic-builder](https://github.com/sudo-suhas/elastic-builder)

**Comment by danpaz** [comment]
@unioah You should be able to override the default key by passing an object as the second argument to bodybuilder.aggregation. For example:

```
bodybuilder()
  .aggregation('cumulative_sum', { buckets_path: 'the_sum' }, 'name_me')
  .build()
```

**Comment by ferronrsmith** [comment]
Added the example from the documentation page above.
