### ISSUE TITLE
Way to toggle filter

### ISSUE THREAD

**Issue by agustik** [danpaz/bodybuilder#150]
Hey there!

I can't see that there is a way to toggle filter/query

query.filter('term', 'myField', 'myValue') only appends to the filter array.

It would be nice to do query.toggleFilter('term', 'myField', 'myValue'); 

Also, is there a way to load elasticsearch query into bodybuilder object?

like
 var query = bodybuilder().loadQueryFromJson(' { "query" :  { ... } } ');

**Comment by ferronrsmith** [comment]
```javascript

// Appends to query.
bodybuilder()
        .query('term', 'myField', 'myValue')
        .build()
```

Short answer for the second part is no. You can't construct a bodybuilder object from ES query DSL

**Comment by agustik** [comment]
Yes. I know how to create a query with filter.
The question is how can i remove the filter? Or is there a way to toggle filter / Remove the filter if it is already on.

**Comment by ferronrsmith** [comment]
That's not supported.

**Comment by agustik** [comment]
Well.. there is still no way to remove the filter if it has been applied..

User clicks "Filter by myFiled:myValue"
```
 builder.filter('term', 'myField', 'myValue')
```
User clicks "Filter by myFiled:myValue" again
```
 // Does the query have the filter already?
 builder.removeFilter('term', 'myField', 'myValue')
```

**Comment by ferronrsmith** [comment]
It all depends on your setup. If you're preserving the state of the builder then no, but if you're recreating the builder each time then it's no.

**Comment by ferronrsmith** [comment]
Also added suggestion in #123 which is to use monkey-patching.

**Comment by agustik** [comment]
Thanks. I might look into that!.

**Comment by johannes-scharlach** [comment]
> Also, is there a way to load elasticsearch query into bodybuilder object?

Actually there is a way to do this, @agustik ! We haven't documented this yet, because nobody knew about it, but with bodybuilder's flexible syntax it's actually quite easy to add object to your query:

```js
const existingQuery = {
  term: { foo: 'bar' }
}

bodybuilder()
  .query('bool', 'must', existingQuery)
  .build()
```
You can even pass in an array of existing queries (because ES allows for that).

This approach won't always get you the simplest queries, but the behaviour of the query is 100% as desired.
