### ISSUE TITLE
query('query_string') no longer takes in an array of fields.

### ISSUE THREAD

**Issue by johnmaretich** [danpaz/bodybuilder#151]
Good Day,

I'm upgrading bodybuilder in our site, which has been a great tool to use with Elasticsearch, as I have upgraded Elasticsearch to 5.x.

The using the code for both BB 1.x and 2.x:

```
var body = bodybuilder();
body.query('query_string', ['name', 'ingredients', 'description', 'brand'], $scope.query);
body.filter('term', 'status', '1');
body.filter('term', 'is_in_stock', 1);
return body.build();
```

1.x generates:
`{"query":{"bool":{"filter":{"bool":{"must":[{"term":{"status":"1"}},{"term":{"is_in_stock":1}}]}},"must":{"query_string":{"query":"fusilli","fields":["name","ingredients","description","brand"]}}}}}`

2.x generates:
`{"query":{"bool":{"filter":{"bool":{"must":[{"term":{"status":"1"}},{"term":{"is_in_stock":1}}]}},"must":{"query_string":{"name,ingredients,description,brand":"fusilli"}}}}}`

With the error: "[query_string] query does not support [name,ingredients,description,brand]"

I'm not sure if its a migration issue and I missed reference to the functionality being removed. I'm working to implement a work around for now but I thought I would raise this as I didn't find another issue related.

Kind Regards

**Comment by ferronrsmith** [comment]
For v2 you can use 

```javascript
bodybuilder().query('query_string', {"query" : "fusilli", "fields" :["name","ingredients","description","brand"]})
  .filter('term', 'status', '1')
  .filter('term', 'is_in_stock', 1).build()
```

Which will generate

```json
{"query":{"bool":{"filter":{"bool":{"must":[{"term":{"status":"1"}},{"term":{"is_in_stock":1}}]}},"must":{"query_string":{"query":"fusilli","fields":["name","ingredients","description","brand"]}}}}}
```

This works for both v1 or v2

**Comment by johnmaretich** [comment]
Great, I didn't try it that way, worked as expected.

Thanks for your support!
