### ISSUE TITLE
tag bodybuilder@2.2.2 have no directory lib

### ISSUE THREAD

**Issue by coolme200** [danpaz/bodybuilder#153]
should run scripts build first ....

**Comment by coolme200** [comment]
![default](https://user-images.githubusercontent.com/1400114/30681343-9d3ddea0-9ed7-11e7-8b97-4e00d31dd213.png)

**Comment by tinder-dyakobian** [comment]
lol wow

**Comment by coolme200** [comment]
2.2.2 ~ 2.2.5 all failed .......

**Comment by ferronrsmith** [comment]
yea i know, currently building the fix.

**Comment by johannes-scharlach** [comment]
uhhh, this was quite the experience... didn't know that the package hadn't been published via travis before. Great teamwork @ferronrsmith 💪

**Comment by ferronrsmith** [comment]
Yea and it's probably because the documentation for travis is so confusing.

**Comment by ferronrsmith** [comment]
Thanks @johannes-scharlach great work ! @coolme200  2.2.6 should be good now.

**Comment by coolme200** [comment]
👍
