### ISSUE TITLE
aggregation of type top_hits not working as docs seem to specify

### ISSUE THREAD

**Issue by labrute974** [danpaz/bodybuilder#159]
It seems that to be able to use the **top_hits** aggregation type, a null value needs to be passed to the field, otherwise field is set to **name**.

*FYI: the examples below are done via the REPL interface in node.*

```
  > // Not what we want:
  > JSON.stringify(body().agg('top_hits', 'test', { size: 1 }).build())
  '{"aggs":{"agg_top_hits_test":{"top_hits":{"field":"test","size":1}}}}'

  > // What we'd expect
  > JSON.stringify(require('bodybuilder')().agg('top_hits', null, 'test', { size: 1 }).build())
  '{"aggs":{"test":{"top_hits":{"field":"","size":1}}}}'
```

Is that by design?

**Comment by johannes-scharlach** [comment]
the way I'd write it is

```js
require('bodybuilder')().agg('top_hits', { size: 1 }, 'test').build()
```
so passing in the argument/object as the second parameter.

This is completely interchangeable with the `null` strategy – for some aggregations a string as the second argument simply doesn't make sense. We've consciously decided to not add any query-specific logic to bodybuilder.

I hope this helps 🙌

**Comment by labrute974** [comment]
Awesome!

That makes sense.
Thanks for the quick reply @johannes-scharlach !
