### ISSUE TITLE
Support for ElasticSearch 6.x?

### ISSUE THREAD

**Issue by ecdeveloper** [danpaz/bodybuilder#166]
Is there a plan on making bodybuilder compatible with ES@6.x?

**Comment by ferronrsmith** [comment]
bodybuilder already has supports (since version 2)

**Comment by ecdeveloper** [comment]
May be worthwhile to update the readme, since currently it says `Currently aims to support the full elasticsearch query DSL for versions 1.x, 2.x, and 5.x.`
