### ISSUE TITLE
Or query doesn't give me expected result

### ISSUE THREAD

**Issue by mlumbroso** [danpaz/bodybuilder#169]
Hello,

Thanks for this great library.

I can't get my head around some query, it seems correct on the paper, but doesn't seem to give a correct output :

```
let body = bodybuilder().orQuery('range', 'processAttempts', { lt: 8, gt: 0 })
                                       .orQuery('bool', b => b.notQuery('exists', 'field', 'processAttempts'));
```
Here is the output request : 

```
{
  "query": {
    "bool": {
      "should": [
        {
          "range": {
            "processAttempts": {
              "lt": 8,
              "gt": 0
            }
          }
        },
        {
          "bool": {
            "must_not": [
              {
                "exists": {
                  "field": "processAttempts"
                }
              }
            ]
          }
        }
      ]
    }
  }
}
```

Basically I want to get the records if `processAttempts` is between 0 to 8 or if it doesn't exist. The output seems correct as far as I can tell.
It gives me 5 results as is.

If I run the 2 queries separately, it gives me 0 results (which is the correct expected result).

It seems like the range doesn't have any effect in case of the OR query (from the results I get, that's my lead).

Could this be a bug of elasticSearch node client or of bodybuilder ? Did I miss something here ?

Thanks for your help :)

PS : Using last versions of elasticsearch-js and bodybuilder

**Comment by ferronrsmith** [comment]
I think the problem here is your missing the `minimum_should_match` property

**Comment by mlumbroso** [comment]
Great, that did the trick :)

Thanks a lot !
