### ISSUE TITLE
_source filter. Fetch only required fields

### ISSUE THREAD

**Issue by shankmr** [danpaz/bodybuilder#170]
Hi,
I have a requirement where I have to send _source field to get only required fields from elastic. 
{
  "_source":  "requestHeader",
  "size":10,
  "from":20
}

Is there any way to achieve this using bodybuilder?

**Comment by ferronrsmith** [comment]
```javascript
bodybuilder()
        .rawOption('_source', 'requestHeader').size(10).from(20).build()
````

It's called **rawOption**

**Comment by shankmr** [comment]
thanks @ferronrsmith

**Comment by ferronrsmith** [comment]
You're welcome @shankmr
