### ISSUE TITLE
Problem nesting query filter under aggregation

### ISSUE THREAD

**Issue by richardwhatever** [danpaz/bodybuilder#172]
When i try and run code like this:

 bb.aggregation('filter', fieldName, aggName, (a) => {
      return a.filter('nested', {path: 'skus'}, (n) => {
		return n.query('terms', { 'material': 'wood' })
		})
        .aggregation('terms', fieldName, aggName)
    })
BodyBuilder errors saying "TypeError: n.query is not a function" but I can't add a query under a filter. Elasticsearch needs it to be a query there, not filter.

**Comment by richardwhatever** [comment]
Quoting @ferronrsmith comment on another issue

> i.e The problem also lies with your query. You are nesting a query inside a filter ...
> 
> Have you tried ?
> 
> ```
>  bb.aggregation('filter', fieldName, aggName, (a) => {
>       return a.filter('nested', {path: 'skus'}, (n) => {
> 		return n.filter('terms', { 'material': 'wood' })
> 		})
>         .aggregation('terms', fieldName, aggName)
>     })
```

The problem is it needs to be a query. The elasticsearch request only works when it is "query", not "filter". If you send filter you get the following error "reason=[nested] query does not support [filter]"

**Comment by ferronrsmith** [comment]
```
bodybuilder().aggregation('filter', 'name', 'test', (a) => {
	return a.filter('nested', {path: 'skus'}, (n) => {
        return bodybuilder().query('terms', { 'material': 'wood' })
})
.aggregation('terms', 'some', 'thing')
}).build()
```

You could also do the above ....

**Comment by richardwhatever** [comment]
Thanks @ferronrsmith , i'm just not sure how else to filter my aggregations for use in a faceted search UI, where the search box query is also used to restrict the facets (not just the facet term filters) - there are no examples I can find that integrate both a search query (e.g. multi_match) and term facets at the same time.

**Comment by ferronrsmith** [comment]
Well if it's needed you can call `bodybuilder()` inside the nest function to create any query you want. My case is really performance, not necessarily functionality. 
I can partially visualize what your saying, but it's hard without an example. Hopefully the samples above should give you a head-start

**Comment by richardwhatever** [comment]
Thanks! I'm working on an alternative approach, but will fall back to above if no success. With respect to bodybuilder... the fact that elasticsearch allows above requirement but bodybuilder won't build it by default... is that an issue?  I'll leave it to you to decide on that. Thanks for your help.

**Comment by ferronrsmith** [comment]
Closing this issue.
Please re-open if you do not feel the question has been answered sufficiently.
