### ISSUE TITLE
Support for search_after?

### ISSUE THREAD

**Issue by ecdeveloper** [danpaz/bodybuilder#173]
Hey guys, 

Are you planning on adding support for [search_after](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-search-after.html)?

**Comment by ferronrsmith** [comment]
Have you tried using **rawOption** ?

```javascript
bodybuilder()
    .size(10)
    .query('match', 'title', 'elasticsearch')
    .rawOption("search_after", [1463538857, "654323"])
    .sort([{
            "date": "asc"
        },
        {
            "_id": "desc"
        }
    ])
    .build()
```

**Comment by ecdeveloper** [comment]
Oh, missed it. It seems to do the thing. Thanks!
