### ISSUE TITLE
Way to Flatten aggregations callbacks

### ISSUE THREAD

**Issue by shawel** [danpaz/bodybuilder#180]
Thank you for this great project. Saved a lot of time. 
Is there a way to somehow flatten aggregation functions (i.e curry the aggs function). This helps to pass around the pointer to the nested aggregate function to be invoked outside.

eg.
Current 
`query.aggregation(type, fields, name, (nested_aggs) => {
		// do something with nested_aggs
               return nested_aggs 
	})`

Proposed 
let aggs
`query.aggregation(type, fields, name, (nested_aggs) => (aggs=nested_aggs))`

**Comment by johannes-scharlach** [comment]
Something similar should already work, but you define the most nested aggregation first:

```js
const nested = bodybuilder().aggregation (...)

const body = bodybuilder().aggregation (type, fields, name, () => nested).build()
```

So what's important is that you return the finished aggregation builder. Every bodybuilder is also an aggregation builder.

Does that work for you?

**Comment by shawel** [comment]
Thanks I will try it. but I think  it could be hard to read since it inverts the flow.  Also nested here is creating new instance of bodybuilder. isn't this different than the aggregation passed down as an  argument.

**Comment by johannes-scharlach** [comment]
Bodybuilder consists of three core builders: one for queries, one for filters and one for aggregations, plus a little scaffolding to tie it all together. When you run `bodybuilder()` you get one object that is aggregation, query and filter builder. In the callback you get an object that can do slightly less (but nothing more).

I've sometimes felt the need that you do too to define a subaggregation 'later' and would like such functionality, but usually I've found the construct with the inverted flow still ok to read.

I'll close this issue and we can reopen it if you run into any serious problems.
