### ISSUE TITLE
Improve modularity of the building process

### ISSUE THREAD

**Issue by Gia90** [danpaz/bodybuilder#181]
It would be great to be able to use bodybuilder (or maybe aggregationBuilder, filterBuilder, queryBuilder) objects as input argument for query/filter/aggregation methods (or maybe new specific methods).
This would improve the flexibility of bodybuilder and consequently the modularity of the code using it.

For example, a possible use case would be this (which is similar to mine):
````
function generateReq(queries, filters, aggregations) {    
    return queries.filters(filters).aggregations(aggregations);    
}
````

Don't know if something like this is already implemented, but I couldn't find any related info in the documentation, the only reference I could find to something similar to this is [here](https://github.com/danpaz/bodybuilder/pull/77/files/6d64f96e2ba7c2e03f2c70ab494f1cb00bb06378#r87007763).

Does it seem a reasonable idea to you?
If not (or even if yes) are there workarounds to still be able to implement a function like the one above using the current version of bodybuilder?
Thank you for your great work.

**Comment by johannes-scharlach** [comment]
Hi Gia,

That's a pretty neat idea! What I think would actually work is to do the following

```js
function generateReq(queries, filters, aggregations) {    
    return Object.assign(bodybuilder(), queries, filters, aggregations).build()
}
```

The whole point of splitting bodybuilder and the others was to have this kind of composability of objects. This should be working with all versions 2.x of bodybuilder.

In my own code-base I'm passing around one bodybuilder object for quite a bit – it might be time to go with an approach that's making use of the modularity like you've suggested here!

If you are having troubles, we can re-open this issue. If you're up for it, it would also be nice to quickly mention queryBuilder, filterBuilder and aggregationBuilder in the `README.md` and explain this merging.

**Comment by Gia90** [comment]
Thank you for the fast reply :)
I was trying to follow your advice, but at first it was not working.

After drilling deeper in the source code, I think I got what you meant:
```javascript
function generateReq(queries, filters, aggregations) {    
    const req = bodybuilder();
    req.getQuery = queries.getQuery;
    req.getFilter = filters.getFilter;
    req.getAggregations = aggregations.getAggregations;
    return req.build();
}
```
where the **queries**, **filters** and **aggregations** arguments are **bodybuilder() objects**.
Is this what you meant?

Now I'm trying to figure out how to use the same approach to define nested aggregations.
Have a nice day :)

**Comment by johannes-scharlach** [comment]
I'm sorry, I meant

```js
function generateReq(queryBuilder, filterBuilder, aggregationBuilder) {    
    return Object.assign(bodybuilder(), queries, filters, aggregations).build()
}
```
where each of them is initialised like `const queryBuilder = require('bodybuilder/lib/query-builder')`, `const filterBuilder = require('bodybuilder/lib/filter-builder')` and `const aggregationBuilder = require('bodybuilder/lib/aggregation-builder')`.

Those are currently not exposed publicly, but will likely not change before the next major version.

Thanks for your patience and apologies for the late reply.
