### ISSUE TITLE
Cannot build valid 'nested' queries in filter context

### ISSUE THREAD

**Issue by cricketts** [danpaz/bodybuilder#183]
From what I can tell, it's not possible to perform a nested query inside of a filter context with BodyBuilder:

```javascript
bodybuilder().orFilter('nested', 'path', 'my_path', b => 
  b.query('term', 'my_path.my_field', 'my_value')
)
```

This doesn't work because `b.query` does not exist, and instead only various filter functions are available. I believe this has to do with being in the "filter context" because of the outer `orFilter()`.

If I try to use `filter`, however:

```javascript
bodybuilder().orFilter('nested', 'path', 'my_path', b => 
  b.filter('term', 'my_path.my_field', 'my_value')
)
```

This results in a `400 Bad Request` from Elasticsearch because filters inside of a nested field is not supported. I am running against Elasticsearch v6.2.

If I use an `orQuery` at the top-level this works fine:

```javascript
bodybuilder().orQuery('nested', 'path', 'my_path', b => 
  b.query('term', 'my_path.my_field', 'my_value')
)
```

However this doesn't work for me because I want my boolean condition to live in the filter context with my other conditions and it's cheaper to perform.

**Comment by johannes-scharlach** [comment]
Thanks for letting us know!

I think it's quite logical that you can't use `query` inside of a filter – after all it's filter context and therefore only filters are available. Let me know if I'm missing something 😃 

As for the bad request with the nested `.filter`: That should surely not happen. I tried addressing this issue in #144, but most users got around the problem for the time being, so I didn't pursue the fix.

One workaround in the mean time (and I realise this is not optimal) would be:

```js
bodybuilder().orFilter('nested', {
  path: 'my_path',
  ...bodybuilder().query('term', 'my_path.my_field', 'my_value').build()
})
```

> and it's cheaper to perform

I've read this in a couple of issues here, but haven't seen any benchmarks. Have you tested the performance difference?

**Comment by cricketts** [comment]
Thanks for the prompt response!

> I think it's quite logical that you can't use query inside of a filter – after all it's filter context and therefore only filters are available. Let me know if I'm missing something 

That's correct for most queries, but not quite true for `nested` documents. Nested queries are performed against the nested objects as if they were indexed as separate documents. In fact, there is no filter context for nested documents, hence the `400 Bad Request`.

For example, this is a valid query, where the nested query is in the filter context of the top-level query:

```
GET my_index/_search
{
  "query": {
    "bool": {
      "filter": {
        "nested": {
          "path": "my_path",
          "query": {
            "term": {
              "my_path.my_field": "my_value"
            }
          }
        }
      }
    }
  }
}
```

> One workaround in the mean time ...

This works great, thank you!

> I've read this in a couple of issues here, but haven't seen any benchmarks. Have you tested the performance difference?

I have not tested this, but I run this query in context of other conditionals, so I would have to move all of my conditionals to the query context, which is not something I will do.

One of the biggest performance differences is that Elasticsearch [caches frequently used filters](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-filter-context.html) whereas queries generate a score and are more expensive to compute.

**Comment by AncientSwordRage** [comment]
I have been trying to follow this issue (as I have a similar one) and I cannot get
```
bodybuilder().orFilter('nested', {
  path: 'my_path',
  ...bodybuilder().query('term', 'my_path.my_field', 'my_value').build()
})
```
to run in the repl at https://bodybuilder.js.org/ is that expected or is it something we can fix?

**Comment by conradoramalho** [comment]
@AncientSwordRage,  you must enter .build() at the end

`bodybuilder().orFilter('nested', {
  path: 'my_path',
  ...bodybuilder().query('term', 'my_path.my_field', 'my_value').build()
}).build()`

**Comment by conradoramalho** [comment]
I solved the problem using:

```
bodybuilder()
        .filter('term', 'agency_id', '115') 
        .filter('nested', {
          path: 'brokers',
          ...bodybuilder()
            .query('term', 'brokers.broker_customer_service_type_id', 2)
            .query('term', 'brokers.broker_id', 167415)
            .build()
        }) 
  	.filter('range', 'profiles.beds', {gte: 2})   
  	.orFilter('term', 'profiles.rent', true)   		 
  	.build()
```

**Comment by quinnlangille** [comment]
@conradoramalho's solve worked for me. If there's no plans on adding nested filter functionality any time soon, this should probably be documented as a workaround :~)
