### ISSUE TITLE
Metadata in aggregation 

### ISSUE THREAD

**Issue by rathish** [danpaz/bodybuilder#184]
Hi,

This module helps to generate complex ES queries in runtime, can you please add Metadata support in the aggregation which helps in our specific cases. 

https://www.elastic.co/guide/en/elasticsearch/reference/current/agg-metadata.html

Thanks,
Rathish

**Comment by ferronrsmith** [comment]
added support for this via `chore/metadata` branch. Feel free to test. I'll merge soon
