### ISSUE TITLE
Cannot filter inside function score query

### ISSUE THREAD

**Issue by nadrane** [danpaz/bodybuilder#192]
Hey there

I'm having some difficulties adding a filter to my query.

```
bodybuilder().query('function_score', {
  script_score: {
    script: {
      source:
        "Do some stuff"
    }
  }
}, b =>
      b
        .orQuery('multi_match', {
          fields: ['organization.name.edge'],
          query: 'freeText',
          fuzziness: 'AUTO'
        })
        .orQuery('multi_match', {
          fields: ['id.edge', 'organization.id.edge'],
          query: 'freeText'
        })
        .filter('term', 'archived', false)
    ).build()
```

I was expecting the above query to generate something like this:

```
{
  "query": {
    "function_score": {
      "script_score": {
        "script": {
          "source": "do some stuff"
        }
      },
      "query": {
        "bool": {
          "filter": [{
            "term": {
              "archived": false
            }
          }],
          "should": [
            {
              "multi_match": {
                "fields": [
                  "organization.name.edge"
                ],
                "query": "freeText",
                "fuzziness": "AUTO"
              }
            },
            {
              "multi_match": {
                "fields": [
                  "id.edge",
                  "organization.id.edge"
                ],
                "query": "freeText"
              }
            }
          ]
        }
      }
    }
  }
}
```

instead I end up with this 

```
{
  "query": {
    "function_score": {
      "script_score": {
        "script": {
          "source": "do some stuff"
        }
      },
      "query": {
        "bool": {
          "should": [
            {
              "multi_match": {
                "fields": [
                  "organization.name.edge"
                ],
                "query": "freeText",
                "fuzziness": "AUTO"
              }
            },
            {
              "multi_match": {
                "fields": [
                  "id.edge",
                  "organization.id.edge"
                ],
                "query": "freeText"
              }
            }
          ]
        }
      },
      "filter": {
        "term": {
          "archived": false
        }
      }
    }
  }
}
```

It looks like the filter statement is not valid after the function score. Elasticsearch actually isn't able to parse the generate query. Perhaps I'm using the API incorrectly? I'd love a little insight. Thank you

**Comment by ferronrsmith** [comment]
not quite. it's a context issue. In any case. Have you ran both queries against your data-set to see what the output subset is ? Are they similar ?

**Comment by nams05** [comment]
@nadrane I am stuck with the same issue. Were you able to figure this out? If yes, what was the solution? Thanks in advance!

**Comment by nams05** [comment]
@ferronrsmith Problem is elasticsearch is not able to parse the query generated. Any help is appreciated

**Comment by arshu16** [comment]
I have been running into the same issue. Unless I create a separate bodybuilder object and spread it, I cannot achieve the nested filtering. This issue should be reopened.

**Comment by danpaz** [comment]
@arshu16 can you confirm the issue is that elasticsearch cannot parse the `query` and `filter` clause at the same level? I believe the required fix here would nest the filter clause inside of query.bool, but it's been some time since I've worked with elasticsearch closely.

**Comment by arshu16** [comment]
@danpaz yes, correct. The fix you proposed is the correct syntax. The filter should automatically be nested under `query.function_score.query.bool` but in the current implementation of bodybuilder, it sits at `query.function_score` level which is then rejected by ES.

**Comment by tomoya-kamaji** [comment]
a
