### ISSUE TITLE
inner_hits in nested queries

### ISSUE THREAD

**Issue by mpadmaraj** [danpaz/bodybuilder#201]
Does this support adding `inner_hits` in nested queries? Example:

```javascript
bodybuilder()
      .query("nested", { path: "app" }, q => {
        return q
          .query("match", "date", "2018-09-06")
          .query("term", "id", 1)
        	
      })
      .rawOption("_source", "")
      .build();
```

In this query how do I add `inner_hits`?

**Comment by ferronrsmith** [comment]
It's always good to search for questions before creating a new issue.

check out : https://github.com/danpaz/bodybuilder/issues/186

**Comment by mpadmaraj** [comment]
Thanks!
