### ISSUE TITLE
bucket_sort in aggregation

### ISSUE THREAD

**Issue by mike123vn** [danpaz/bodybuilder#202]
does bodybuilder support bucket_sort?

I have an issue when converting below query to body query

{
    "size": 0,
    "query": {
      "bool": {
        "must": [
          {"exists": {"field": "highestResult"}},
        ]
      }
    },

    "aggs": {
      "by_user_id": {
        "terms": {
          "field": "userId"
        },
        "aggs": {
          "totalCorrectAnswers": {
            "sum": {
              "field": "highestResult.totalCorrectAnswers"
            }
          },
          "timeSpent": {
            "sum": {
              "field": "highestResult.timeSpent"
            }
          },
          "totalExams": {
            "sum": {
              "field": "totalExams"
            }
          },
          "score": {
            "avg": {
              "field": "highestResult.score"
            }
          },
          "timeSpentAvg": {
            "avg": {
              "field": "highestResult.timeSpentAvg"
            }
          },
          "result_bucket_sort": {
            "bucket_sort": {
              "sort": [
                {
                  "totalCorrectAnswers": {
                    "order": "desc"
                  },
                  "timeSpent": {
                    "order": "asc"

                  },
                  "totalExams": {
                    "order": "asc"

                  }
                }
              ],
              "size": 3
            }
          }
        }
      }
    }
  }

**Comment by ferronrsmith** [comment]
```javascript
bodybuilder()
    .aggregation('terms', 'userId', 'by_user_id', (a) => {
        return a.aggregation('sum', 'highestResult.totalCorrectAnswers', 'totalCorrectAnswers')
            .aggregation('sum', 'highestResult.timeSpent', 'timeSpent')
            .aggregation('sum', 'totalExams', 'totalExams')
            .aggregation('avg', 'highestResult.score', 'score')
            .aggregation('avg', 'highestResult.timeSpentAvg', 'timeSpentAvg')
            .aggregation('bucket_sort', {
                "sort": [{
                    "totalCorrectAnswers": {
                        "order": "desc"
                    },
                    "timeSpent": {
                        "order": "asc"

                    },
                    "totalExams": {
                        "order": "asc"

                    }
                }],
                "size": 3
            }, 'result_bucket_sort')
    })
    .build()
```

I'll say this again. **READ THE DOCUMENTATION**. There is a lot of examples there or in previous issues.

Use https://bodybuilder.js.org/ to test your constructions.
Documentation is her : https://bodybuilder.js.org/docs/
