### ISSUE TITLE
Multi GET API /_mget endpoint

### ISSUE THREAD

**Issue by mauxtin** [danpaz/bodybuilder#205]
Is there any way to target this endpoint? I cannot find anything in the documentation so I suppose it is not supported but is there any way to target it in a way similar to the rawOption?

What I want to do is get documents based on their ids.

Docs: https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-multi-get.html

**Comment by johannes-scharlach** [comment]
You're right, this is not yet supported.

I don't really see where bodybuilder would simplify anything over

```js
esClient.mget({
  body: {
    docs: myIdsArr.map(id => ({ _id: id}))
  }
})
```

what would you expect bodybuilder to do?

**Comment by ferronrsmith** [comment]
bodybuilder is **an elasticsearch query builder**
