### ISSUE TITLE
Simple Min, Max Aggregation

### ISSUE THREAD

**Issue by marslan390** [danpaz/bodybuilder#209]
How to convert the following elastic query from bodybuilder. Thanks
{
  "query": {
    "term": {
      "campaign.id": 1
    }
  },
  "aggs" : {
        "max_date" : { "max" : { "field" : "start_date" } },
        "min_date" : { "min" : { "field" : "end_date" } }
    }
}

**Comment by ferronrsmith** [comment]
```javascript
bodybuilder()
        .query('term', 'campaign.id', 1)
        .aggregation('max', 'start_date', {}, 'max_date')
        .aggregation('min', 'end_date', {}, 'min_date')
        .build()
```


```json
{
  "query": {
    "term": {
      "campaign.id": 1
    }
  },
  "aggs": {
    "max_date": {
      "max": {
        "field": "start_date"
      }
    },
    "min_date": {
      "min": {
        "field": "end_date"
      }
    }
  }
}
```

**READ THE DOCUMENTATION : https://bodybuilder.js.org/docs/**
