### ISSUE TITLE
Escaped Characters

### ISSUE THREAD

**Issue by refayathaque** [danpaz/bodybuilder#210]
Thank you writing this very useful library!

I am having issues with passing along escaped characters in my searches, could you kindly help? The issue I am having is detailed below, it was our communication with the team elasticsearch:

> We are using the wildcard query to look for domains that are meeting the user provided input. E.g., when a user types in xyz they see a list of domains with xyz in it, this can be xyz.com, helloxyz.com, xyzworld.com, etc.

> Furthermore, if the user inputs something with a period, our query will work for the most part, E.g., if the user input xyz1 elasticsearch will return xyz1.com, however, if the user input xyz1.com elasticsearch will NOT return xyz1.com.

> So at first, we were led to believe that the wildcard query cannot support periods, however, upon further testing, we saw that was not the case. E.g., when a user types in xyz.com, we will get all domains with xyz.com like helloxyz.com and worldxyz.com.

> We think elasticsearch has an issue with looking up a number followed up an escaped character.

> Furthermore, we can't input dashes and find values with dashes in them, e.g., if we input xyz-goodbye we will not get xyz-domain.com.

> So there is also the issue of characters like dashes.

> We are using bodybuilder.js and our query is:

> .query('wildcard', 'url', '*'+text+'*')

> .query('wildcard', 'url', '*xyz1.*') will not return xyz1.com

> Any help is highly appreciated, thank you.

https://github.com/elastic/elasticsearch/issues/34822

**Comment by ferronrsmith** [comment]
Did you try debugging ? From what I am seeing there seems to be a lack of understanding or what the **wildcard query does**. Wildcard only support :
`*` - which matches any character sequence (including the empty one) 
`?`which matches any single character

**READ THE DOCUMENTATION** : https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-wildcard-query.html

I think what you're looking is maybe "regexp query" - https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-regexp-query.html


```javascript
    .query('regexp', 'url', 'xyz1.*') // will return xyz1.com
```

**Comment by refayathaque** [comment]
@ferronrsmith thank you for ^, the reason I am using a wildcard is that I need my users to be able to type in ANYTHING and find the search result. E.g., I need them to be able to find helloworld1.america.com by just typing in `world1.` or `1.america.`. I tried what you recommended up top but it doesn't seem to be working. The problem seems to be with an escaped character following a number.

**Comment by ferronrsmith** [comment]
You can't do what you want with wildcard. Wildcard replaces a single character, not **ALL**. What you want is a **regexp**. e.g.

User types in ...

`world1` ... you apply regex sauce to it, so you do .... `.+${user_entry}.+`. The problem with regex is that it's very slow can be slow when doing term look-ups

There's also prefix/phrase_match querying.

> i.e. This isn't a bodybuilder issue. bodybuilder does not modify the input, all it does is constructs query, its query builder. This is an implementation issue.

**Comment by refayathaque** [comment]
Also, I am running 6.2 on AWS in a t2.small.elasticsearch

**Comment by refayathaque** [comment]
Thank you guys, but I am working with someone who is able to use the wildcard query to find results for things like `xyz1.com` by having the wildcard input be `xyz1.`

Please see: https://github.com/elastic/elasticsearch/issues/34822

**Comment by ferronrsmith** [comment]
👍🏾
