### ISSUE TITLE
nested bool with one query

### ISSUE THREAD

**Issue by uxnow** [danpaz/bodybuilder#211]
hello, there.

nested bool with one query seems not work, so what is the best pratice? thank you!

![image](https://user-images.githubusercontent.com/2252992/48182028-c23fdc80-e364-11e8-8bf9-9601aa287a8e.png)

**Comment by ferronrsmith** [comment]
Don't nest ?

**Comment by uxnow** [comment]
thank you for so fast response. I am working on something like auto query builder, it really happens.

**Comment by uxnow** [comment]
thank you very much for your advice, it really help!

**Comment by ferronrsmith** [comment]
You’re welcome. If there is anything else, feel free to open an issue. Thanks for using bodybuilder 😉
