### ISSUE TITLE
what is the syntax to use global aggregation with sub-aggregations?

### ISSUE THREAD

**Issue by ukankal** [danpaz/bodybuilder#213]
Below is the query for global aggregation taken from [docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-global-aggregation.html),
curl -X POST "localhost:9200/sales/_search?size=0" -H 'Content-Type: application/json' -d'
{
    "query" : {
        "match" : { "type" : "t-shirt" }
    },
    "aggs" : {
        "all_products" : {
            "global" : {}, 
            "aggs" : { 
                "avg_price" : { "avg" : { "field" : "price" } }
            }
        },
        "t_shirts": { "avg" : { "field" : "price" } }
    }
}
'
what would be the bodybuilder syntax to build this aggregation?

**Comment by johannes-scharlach** [comment]
```js
bodybuilder()
        .query('match', 'type', 't-shirt')
        .aggregation('global', {}, 'all_products', a =>
                    a.aggregation('avg', 'price', 'avg_price', )
        )
        .aggregation('avg', 'price', 't_shirts')
        .build()
```
you can play around with that on https://bodybuilder.js.org/

**Comment by ukankal** [comment]
Thanks for the help Johannes.
