### ISSUE TITLE
How to set priority to 'and' operator?

### ISSUE THREAD

**Issue by rmaniraj** [danpaz/bodybuilder#216]
Hello,
I want to run a search query like below,

`
SELECT * FROM AIRINGS WHERE SID='XXXX' AND START<111 AND END>222 AND
MOVIEID IN ('AAA', 'BBB', 'CCC')
`
So, i am trying to achieve this as below,
```javascript
const mids = ['AAA', 'BBB', 'CCC'];
const reqBody = bodyBuilder()
	.query('bool', b =>
		b
		.query('match', 'sid', 'XXXX')
		.query('match', 'lang', 'en')
		.query('range', 'start', {lte: 111})
		.query('range', 'end', {gte: 222}),
	)
	.query('bool', mids => {
	for (const mid of mids)
		tms.orFilter('match', 'movieId', mid);
	return mid;
	})
         .size(5)
	.build();
```
Still, i am getting responses which is not respecting 'AND' operator for SID.
After adding range filter only my result set get polluted with other records.
Could anyone help me to understand if i am doing anything wrong in this query.

**Comment by ferronrsmith** [comment]
it would help to provide a bit more info or a working query.

**Comment by danpaz** [comment]
You have `mids` defined in 2 places, my guess is you did not mean to pass it as an argument to the query callback? Try playing with the query in the sandbox at https://bodybuilder.js.org.

Closing as not actionable.
