### ISSUE TITLE
Should inside must

### ISSUE THREAD

**Issue by Igorpollo** [danpaz/bodybuilder#217]
Hi..
I'm trying to do this query but nothing worked yet.
Someone can help?

        {"query": {
        "bool": {
          "filter": {
            "bool": {
              "must": [
                {"bool": {
                    "should": [
                        {"match": {"provider": "in"}},
                        {"match": {"provider": "yt"}}
                    ]
                }},
                {
                  "range": {
                    "subscribers": {
                      "gt": 1
                    }
                  }
                }
              ]
            }
          }
        }
      }
    }

**Comment by ferronrsmith** [comment]
```javascript
bodybuilder()
        .filter('bool', b => 
               b.orFilter('match', 'provider', 'in')
                .orFilter('match', 'provider', 'in')
               )
         .filter('range', 'subscribers', {'gt' : 1})
        .build()
```

>>> https://bodybuilder.js.org is your friend.
Docs are here : https://bodybuilder.js.org/docs/

The tests contains lots of examples. not to mention searching previous issues.
