### ISSUE TITLE
How to stop tokenize on filter search?

### ISSUE THREAD

**Issue by ragu-nathan** [danpaz/bodybuilder#218]
Hi,
I have an id field which has hyphens(-) in it. When I try to write a filter search query against that field, it is not working as expected. Elasticsearch is doing tokenize and search with all words and returned the results which I don't want. I would like to get the exactly matched documents. Please find more details below,
`bodybuilder()
        .query('match', 'appId', 'A983-5600-433')
        .build()`
it returns, all the matching documents with all three words, 'A983', '5600', and '433'.

If i try with term query it is not returning any results,
`bodybuilder()
        .query('term', 'appId', 'A983-5600-433')
        .build()`

Can you please help me with this?

Thanks.

**Comment by johannes-scharlach** [comment]
Hi @ragu-nathan, you can see the output of bodybuilder by using our playground here https://bodybuilder.js.org/

I think otherwise this is an elasticsearch question, not specific to bodybuilder.
