### ISSUE TITLE
Cannot read property 'hasFilter' of undefined

### ISSUE THREAD

**Issue by bertyhell** [danpaz/bodybuilder#223]
If anyone else runs against this error message:
```
Cannot read property 'hasFilter' of undefined
```

It might be because you are not returning the query object in your nested function.

Wrong:
```javascript
q.orFilter("bool", (partialQuery) => {
	if (addressInfo.street) {
		partialQuery = partialQuery.filter(...);
	}
	if (addressInfo.houseNr.lte > 0) {
		partialQuery = partialQuery.filter(...);
	}
});
```

Correct:
```javascript
q.orFilter("bool", (partialQuery) => {
	if (addressInfo.street) {
		partialQuery = partialQuery.filter(...);
	}
	if (addressInfo.houseNr.lte > 0) {
		partialQuery = partialQuery.filter(...);
	}
	return partialQuery;    // <<<<<<<<<<<<<< your arrow function needs to return the partial query object
});
```

This isn't very clear in the examples, since everything is done in a functional way: 
```javascript
q.orFilter('bool', b => b
	.filter('query_string', 'street', '*Langestraat*')
	.filter('range', 'houseNr', { gte: 0, lte: 100 })
);
```

If you wrap your arrow function with curly brackets, you need an extra return to pass the query object back to the parent.

@danpaz You can close this issue, just thought it might help other people faced with the same issue.

**Comment by ferronrsmith** [comment]
Actually that's really a ES6 issue
(param1, param2, …, paramN) => { statements } 
(param1, param2, …, paramN) => expression
// equivalent to: => { return expression; }


The statement needs a **return**, while the expression doesn't. That's just JS syntactic sugar, has nothing to do with bodybuilder.

**Comment by danpaz** [comment]
@bertyhell thanks for the note. While it is an es6 detail I added a small clarification to the docs in https://github.com/danpaz/bodybuilder/commit/68af03f8661d5586b9edf77d585faec3fc623443.

**Comment by bertyhell** [comment]
Yes I knew that, the error message is just not very helpful and tmy mistake was hard to spot

Thank you for adding the clarifying note. 

Would it be helpful if I made a PR to throw a more helpful message when that error occurs? Eg:
```
Cannot read property 'hasFilter' of undefined. Are you returning the builder object inside your nested functions? 
```

**Comment by johannes-scharlach** [comment]
I think it would make sense to check the type/properties of any nested query/filter and provide useful feedback. This is all centralised here: https://github.com/danpaz/bodybuilder/blob/master/src/utils.js#L111
