### ISSUE TITLE
Creating a filter aggregation dynamically? 

### ISSUE THREAD

**Issue by dres-cifuentes** [danpaz/bodybuilder#224]
Hello! 

So I'm trying to create a query based on the amount of filter items selected. 
So the default filter for a specific list type looks like:

```js
bodybuilder()
    .aggregations('terms', 'listingType.keyword', 'Type')
    .build()
```

Which works as expected. I have the aggregation bucket I need. 

What If an item was selected? I'd want to add that filter to it.

This is what I want it to look like:

```js
bodybuilder()
    .addFilter('term', 'itemTypeId', 2)
    .aggregations('terms', 'listingType.keyword', 'Type')
    .build()
```

Or if multiple items were selected then..

```js
bodybuilder()
    .addFilter('term', 'itemTypeId', id)
    .addFilter('term', 'moo.keyword', moo)
    .addFilter('term', 'make.keyword', make)
    .aggregations('terms', 'listingType.keyword', 'Type')
    .build()
```

I have an array of selected filters. I figured I could do something like:

```js
const activeFilters = [{type: 'make.keyword, value: 'SAMSUNG'}, {type: 'moo.keyword', value: 'moo'}]

if (activeFilters) {
    activeFilters.map(item => {
        addFilter(item.type, item.value)
    }
}

//OR

bodybuilder()
    activeFilters.map(item => addFilter(item.type, item.value)
    .aggregation('terms' , 'listingType.keyword', 'Type')
    .build()

```
Something along those lines. Any recommendations?

Thanks!

**Comment by ferronrsmith** [comment]
what u have looks fine to me. There isn't any right or wrong way to do this. Whatever is easiest for you.

**Comment by dres-cifuentes** [comment]
Thanks for your quick response!
Unfortunately I'm having syntax issues.
Example: 
```js
const build = bodybuilder()
    .sampleArray.map(item => addFilter(item.type, item.value))
    .aggregation('terms', searchType, label)
    .build();
```
Gives me a `'addFilter' is not defined` error

**Comment by ferronrsmith** [comment]
it would be

```javascript
const activeFilters = [{type: 'make.keyword', value: 'SAMSUNG'}, {type: 'moo.keyword', value: 'moo'}]
const builder = bodybuilder();
activeFilters.map(item => builder.addFilter(item.type, item.value))
builder.aggregation('terms', 'listingType.keyword', 'Type').build()   


```

**Comment by dres-cifuentes** [comment]
good call, i don't use `forEach` often and sometimes forget it exists

but unfortunately the suggestion you gave me didn't work

So I tried:

```js
const buildQueryAggregations = (searchType, label) => {
  const sampleArray = [{ type: 'itemTypeId', value: 2 }];

  const builder = bodybuilder();
  sampleArray.forEach(item => builder.addFilter(item.type, item.value));
  return builder.aggregation('terms', searchType, label).build();
};

```

and I get an ES error:

![Screen Shot 2019-04-23 at 6 02 43 PM](https://user-images.githubusercontent.com/48491711/57165258-298e9480-6dbc-11e9-844f-8e7688438c5b.png)

**Comment by ferronrsmith** [comment]
The error doesn't seem to be coming from ES, but rather an API you are using. Hard to say without know exactly what's being passed in vs returned. Can you provide a bit more context ?

**Comment by dres-cifuentes** [comment]
i'm sorry, that was the wrong screenshot

in any case, i figured it out and updated it in my comment above. thanks for your help 👍

**Comment by ferronrsmith** [comment]
ok np 👍
