### ISSUE TITLE
Possible to combine certain bucket items?

### ISSUE THREAD

**Issue by dres-cifuentes** [danpaz/bodybuilder#226]
I'm trying to create a color filter. The colors being returned are mostly normal but there's a bunch of other off ones. Example, my results show up like this:

 ```js
{ key: "WHITE", doc_count: 300 }, 
{ key: "OFFWHITE", doc_count: 2 }, 
{ key: "SUPER WHITE", doc_count: 1 }
```

My bodyBuilder use is:
```js
build.aggregation('terms', 'colors.keyword', 'Color', { size: 100 }).build();
//=>
aggs: {
    Color: {
        terms: {
            field: 'colors.keyword',
            size: 100,
        },
    },
}

```

I want to combine anything that includes 'white' together into one bucket. Same with the other colors that have a doc_count above 20 like "BLACK", "RED",  "BLUE", etc.

- Is this possible?
- Is this possible with bodybuilder?

**Comment by ferronrsmith** [comment]
Not possible. The ideal scenario would have been to preprocess the colors before insertion them..

```json
{ color : 'offwhite', primary : 'white' }
```

Or post-process the buckets, when they are returned. You can use the script ([painless](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#search-aggregations-bucket-terms-aggregation-script)). 

> **Be aware of the performance penalties when using painless**

**Comment by dres-cifuentes** [comment]
Do scripts work with body builder?

**Comment by ferronrsmith** [comment]
```javascript
bodybuilder()
    .aggregation('terms', null, 'Color', { script: {
                    source: "doc['colors.keyword'].value",
                    lang: "painless"
                }, size : 100})
    .build();
```
