### ISSUE TITLE
Getting exception while building query

### ISSUE THREAD

**Issue by RajanGupta667** [danpaz/bodybuilder#227]
I am using bodybuilder library to build query after body.build getting Object but contains below exception
"Exception: TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them at Function.invokeGetter"

could you please suggest something @danpaz

**Comment by danpaz** [comment]
@RajanGupta667 can you share a code snippet that triggers the error? And are you using `use strict` in your code?

**Comment by danpaz** [comment]
@RajanGupta667 let us know if you have any additional details. Closing for now.
