### ISSUE TITLE
Using nested bool with single query

### ISSUE THREAD

**Issue by juliancode** [danpaz/bodybuilder#228]
Hi I notice that you strip the must array down if a bool contains only one query (which breaks the query), I'm wondering what the best practice would be to achieve a conditional bool query which sometimes contains a single query and sometimes multiple.

Here is an example 

```
bodybuilder().query('nested', {path: 'track'}, q =>
  q.query('bool', b => {
    if (true) {    
      b.query('terms', 'track.mood', ['happy', 'sad'])
    }
    if (false) {
      b.query('terms', 'track.genre', ['hiphop', 'rock'])
    }
    return b
  })
).build()
```

If both are true this will work, however for scenarios where only one is true it won't work. Is there any harm in allowing bools with only a single query must inside?

Thanks for your time

**Comment by ferronrsmith** [comment]
Why didn't you just do :

```javascript
bodybuilder().query('nested', {path: 'track'}, q => {
    if (true) {    
      q.query('terms', 'track.mood', ['happy', 'sad'])
    }
    if (false) {
      q.query('terms', 'track.genre', ['hiphop', 'rock'])
    }
    return q
  }
).build()
```

Your above query is doing a "double nest"
