### ISSUE TITLE
how to filter list 

### ISSUE THREAD

**Issue by RajanGupta667** [danpaz/bodybuilder#230]

**Comment by RajanGupta667** [comment]
I want to filter list, in that item list id should be there 
i.e which item has id return that only
how to write query for this.

**Comment by ferronrsmith** [comment]
It's good to read the Elasticsearch documentation to have a basic idea of what it is you want to do.


```javascript
bodybuilder()
        .filter('terms', 'id', [1,2,3,4])
        .build()
```

**Comment by RajanGupta667** [comment]
Can I write

bodybuilder()
        .filter('terms', 'id')
        .build()

Bcoz I just want to know the 'id' has some value

What values it will contain I don't have idea about that.

Thanks in advance.

**Comment by ferronrsmith** [comment]
You want to return a records that have a the id field ? Kinda like exists https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-exists-query.html

**Comment by RajanGupta667** [comment]
Yes u got me correct.
But how to write that exist query using bodybuilder format.

**Comment by ferronrsmith** [comment]
```javascript
bodybuilder()
        .filter('exists', 'id')
        .build()
```
