### ISSUE TITLE
Support Suggesters

### ISSUE THREAD

**Issue by lintaonz** [danpaz/bodybuilder#231]
Hi,

Does bodyBuilder plan to support [Suggesters](https://www.elastic.co/guide/en/elasticsearch/reference/current/suggester-context.html) in the roadmap?

Thanks,

Tao

**Comment by ferronrsmith** [comment]
library is mostly focused on the Query DSL and not really Suggesters. You can essentially write any query, but how much will bodybuilder do for might be less with suggesters, I suggest [elastic-builder](https://github.com/sudo-suhas/elastic-builder)

**Comment by danpaz** [comment]
Agreed, bodybuilder will remain focused on building query json rather than being a general purpose client.

**Comment by georgyfarniev** [comment]
@danpaz but bodybuilder is intented to simplify building of query, isn't it? Then why it's not possible to create suggestion, since it part of elasticsearch query DSL?
