### ISSUE TITLE
issue related to aggregation

### ISSUE THREAD

**Issue by swetarai763** [danpaz/bodybuilder#232]
i need to understand this clause which is written by using bodybuilder

body.aggregation('terms', underfined, 'terms', elasticAggregationHelper.termOptions('type','_count'));

I am not able to understand this termOptions and not able to find it on bodybuilder site 
could you please guide me @danpaz 
Thanks

**Comment by ferronrsmith** [comment]
https://bodybuilder.js.org/docs/#aggregation

**Comment by swetarai763** [comment]
Hi
I have go through to this doc but not able to understand the last clause
i.e termOptions
Could you please guide.

Thanks,
sweta

**Comment by ferronrsmith** [comment]
The last parameter is for nested aggregation (agg with-in an agg /sub agg). 
A simple example would be this. Let's say I'm generating an aggregation for tags, but with-in that aggregation I want to aggregation the publishers of those tags.

> You can think of it as a sub-query

I'd do something like this :

```javascript
bodybuilder()
.aggregation('terms', 'tags.keyword', { size: 10 }, 'top-tags', (a1) => {
      return a1.aggregation('terms', 'publishers.keyword', { size: 10 }, 'top-publishers')
    }).build()
```

```json
{
  "aggs": {
    "top-tags": {
      "terms": {
        "field": "tags.keyword",
        "size": 10
      },
      "aggs": {
        "top-publishers": {
          "terms": {
            "field": "publishers.keyword",
            "size": 10
          }
        }
      }
    }
  }
}
```
