### ISSUE TITLE
Composite Aggregation - Specifying sources

### ISSUE THREAD

**Issue by anusha5695** [danpaz/bodybuilder#234]
Is it possible to specify composite source for an aggregation of type "composite", instead of a raw JSON?

bodyBuilder().aggregation("composite",SOURCE_FIELDS,"aggregation_name");

Currently I'm specifying the composite source fields as RAW JSON like:

SOURCE_FIELDS = [ {"product_agg": { "terms": {"field":"product"}}}, 
                                    {"sales_agg": { "terms": {"field":"cost_per_month"}}} ]

**Comment by ferronrsmith** [comment]
no, not the answer you want, but with flexibility comes trade-offs.
