### ISSUE TITLE
Possible to do a multiple range query?

### ISSUE THREAD

**Issue by dres-cifuentes** [danpaz/bodybuilder#235]
So I have an aggregation I'm trying to build. One of these includes an array of `from` and `to` values. Looks like:

`const sampleArray = [{from: 500, to: 600}, {from: 601, to: 700}]`

Without bodybuilder, I can build my query this way:

```js
  const generateRangeQuery = () => {
          return sampleArray.map(value => ({
            range: {
              [searchType]: {
                gte: value.from,
                lte: value.to,
                boost: 2.0,
              },
            },
          }));
        };
  const rangeQuery = {
          query: {
            bool: {
              should: generateRangeQuery(),
              minimum_should_match: 1,
              boost: 1.0,
            },
          },
        };

```

How can I accomplish the same thing but with bodybuilder?

If not, is it possible to add my `rangeQuery` to my current build? I have a function with multiple `build.addFilters()` to build my aggregations, I need to be able to add a multi range query to it.

Thank you!

**Comment by danpaz** [comment]
@dres-cifuentes is this what you need?

```js
const body = bodybuilder();
[{from: 500, to: 600}, {from: 601, to: 700}].forEach((value) => {
	body.orQuery('range', 'searchType', {gte: value.from, lte: value.to, boost: '2.0'});
})
body.queryMinimumShouldMatch(1)
body.build(); 
```

**Comment by dres-cifuentes** [comment]
YES! thank you! :D
