### ISSUE TITLE
Ease of creating multiple match queries

### ISSUE THREAD

**Issue by joshkpeterson** [danpaz/bodybuilder#239]
New to elasticsearch and this library, so please point out if I'm missing something that will make this more simple. But I may have a suggestion for how this library could work.

My use case is I will have a form that has a lot of fields. I want to serialize the fields and build an ES query. Most of the time these fields are just implicitly an 'AND'. Many of the fields are not required, so sometimes they won't all have value input.

Currently the only way to do this with bodybuilding is by chaining multiple .query() statements together. **Why not just let me pass in an object to query()?** If you do this currently, it doesn't create a bool with nested must's, it just creates a match query with multiple items in the object, which is invalid ES DSL.

So, to unpack what I just said:
```
bodybuilder().query('match', { foo: "bar", moo: "mar"}).build()

// stringified:
//'{"query":{"match":{"foo":"bar","moo":"mar"}}}'
// this is invalid DSL
```

Instead I have to loop over the object containing my serialized field values, invoking query() for each.

This is awkward, the chaining isn't really conducive for doing things programmatically. At this point I might as well create the query DIY. Which I might end up doing, but it would be nice to keep bodybuilder around for convenience, especially if I end up needing to add other types of queries.

**Comment by ferronrsmith** [comment]
Have your tried using a each/forEach loop ? It’s not hard to iterate over an array chaining match queries

**Comment by joshkpeterson** [comment]
I have, my feedback is just at that point, there is no added convenience using bodybuilder vs constructing the object myself with the loop. It would be great to pass an object into query() with multiple items and have it return the correct, valid DSL.

**Comment by ferronrsmith** [comment]
I understand your feedback, even though I don't agree with it. bodybuilder isn't the end all/do all DSL generation library. There are a lot complex cases where it's better to use the raw DSL, but for most use-cases it's sufficient. 

The choice in the end is yours. The library is an extension of the DSL, not a replacement. While you might think it's limiting/awkward; to me that what makes it very powerful. It doesn't force you to conform to a particular style/form (having to learn something new). It's just simple syntactic sugar over already rich DSL/
