### ISSUE TITLE
Single AND inside a BOOL

### ISSUE THREAD

**Issue by don-miguel** [danpaz/bodybuilder#241]
Given the input;
```
bodybuilder()
  .query("bool", b => {
    return b.andQuery("terms", "people", "abc")
  })
  .build()
```
I get the output;
```
{
  "query": {
    "bool": {
      "query": {
        "terms": {
          "people": "abc"
        }
      }
    }
  }
}
```
which is not a valid query. This behavior is not present if you change the inner `andQuery` to an `orQuery` or a `notQuery` in which case it outputs a valid query:
```
{
  "query": {
    "bool": {
      "should": [
        {
          "terms": {
            "people": "abc"
          }
        }
      ]
    }
  }
}
```
I understand this query could be simplified, however, my use case builds these queries dynamically and there does not appear to be support for adding a `rawOption` to a sub query, in which case i could add the necessary subquery myself.

**Comment by ferronrsmith** [comment]
You can use `rawOption` in a subquery, but it still wouldn't work.

E.g.

```javascript

var inner = bodybuilder().rawOption('query', {
    "bool": {
      "must": [
        {
          "terms": {
            "people": "abc"
          }
        }
      ]
    }
  })

bodybuilder()
  .query("bool", b => {
    return inner
  })
  .build()
```

This isn't possible because of the checks in the construction logic

**Comment by johannes-scharlach** [comment]
@ferronrsmith I'm wondering if it's worth keeping this open. I think @don-miguel is describing a legit use case and the construction logic in bodybuilder is flawed.

@don-miguel just one question out of curiosity: Why are you not able to do

```js
const builder = bodybuilder()
builder.andQuery("terms", "people", "abc")

const result = builder.build()
```

The nesting with `bool` was not always a core feature of bodybuilder and you can usually get pretty far without it. Nesting an `andQuery` just within a bool query doesn't seem like any obvious advantage to me right now.

**Comment by ferronrsmith** [comment]
@johannes-scharlach I see this as an edge, I consequence of us flattening to top-level "must" block. We can't ideally catch all of them, so @don-miguel can work around this by checking how many **andQuery** he has and determine when to nest.

**Comment by don-miguel** [comment]
FWIW I have my issue solved on my fork (https://github.com/danpaz/bodybuilder/compare/master...don-miguel:dont-unwrap) and although im not sure it involves actual breaking changes (the generated queries are functionally the same), it does break a number of tests.
