### ISSUE TITLE
es7 introduced breaking change for 'filterMinimumShouldMatch'

### ISSUE THREAD

**Issue by Shugardude** [danpaz/bodybuilder#243]
We are upgrading to es7 and we're running into an issue with the `filterMinimumShouldMatch`method. With the new ES version, the default value in certain situations for `minimum_should_match` is no longer 1, instead it's 0.
https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#_the_filter_context_has_been_removed

The logic in bodybuilder removes `minimum_should_match` if there is only one should filter, but we need this value to explicitly equal 1, otherwise the should filter is ignored in the case that there is also a must filter. Can you add a way to override the behavior in the code that removes  `minimum_should_match` when there is only one should filter?

```
{
  "body": {
    "query": {
      "bool": {
        "filter": {
          "bool": {
            "must": {
              "terms": {
                "title": [
                  "foo"
                ]
              }
            },
            "should": [
              {
                "terms": {
                  "name": [
                    "foo"
                  ]
                }
              }
            ],
            "minimum_should_match": 1 // in es7, without this, the should filter is ignored
          }
        }
      }
    }
  }
}
```

**Comment by ferronrsmith** [comment]
Not sure I understand what you're saying. A should with one value `minimum_should_match:1` is no different than a must. If the value of the should is 1, then add it to the **must**, if it's greater then use the should.

**Comment by Shugardude** [comment]
Please see the first answer in this thread about the changes to the default value:
https://stackoverflow.com/questions/48984706/default-value-of-minimum-should-match

My understanding was that prior to es 7, query context would default `minimum_should_match` to 0, but filter context would default to 1. As you pointed out in your comment:
**The distinction between queries and filters is now decided in Lucene depending on whether queries need to access score or not**
I think this change is why the filter context no longer defaults the `minimum_should_match` value to 1, but with es 7,  is now 0 like the query context. If you read further in the paragraph you quoted from, you see:
"As a result bool queries with should clauses that don’t need to access the score will **no longer set their minimum_should_match to 1.**"

As for your suggestion that i change the should to a must when there is only one filter, that does not work with how we implemented our code. We construct complex dynamic queries, where it would not be easy to count filters beforehand. Unfortunately until this is fixed, to get around this issue, I am going to have to recursively loop through the es query that the library produces in order to add the `minimum_should_match` value to each filter that needs it.

**Comment by ferronrsmith** [comment]
I understand

**Comment by ferronrsmith** [comment]
support added

```javascript
bodybuilder.filterMinimumShouldMatch(1, true)
```

**Comment by Shugardude** [comment]
Thanks, that was quick! Really appreciate the help!

**Comment by ferronrsmith** [comment]
You’re welcome 👍🏾

**Comment by ChenJhua** [comment]
Hello, I have also encountered this problem. Is there a better solution? When I only have one `should`, the `minimum_should_match `default value is also 0
