### ISSUE TITLE
Option to clone a body

### ISSUE THREAD

**Issue by wa4-fearless-otter** [danpaz/bodybuilder#246]
There should be an option to clone a body and mutate it without mutating the old body.
Something like this:

```javascript
// {"size":2}
const a = bodybuilder()
  .size(2);

// {"size":2,"from":1}
bodybuilder(a.build())
  .from(1)
  .build();
```
In this example `a` should still only contain `size`. I think the new argument in bodybuilder should be a json string an not a bodybuilder instance because this would support hardcoded jsons too.

**Comment by ferronrsmith** [comment]
There are so many tools that provide this functionality.

```javascript
//lodash
_.clone()
_.cloneDeep()

// raw JS
const clone = Object.assign( {}, bodybuilder);
```

**Comment by danpaz** [comment]
> I think the new argument in bodybuilder should be a json string an not a bodybuilder instance because this would support hardcoded jsons too.

I don't think it would be straightforward to produce a bodybuilder instance from JSON, especially with multiple levels of nesting. The only option I see is to clone the bodybuilder instance as shown above.

**Comment by wa4-fearless-otter** [comment]
@ferronrsmith I tried your suggestion but it doesn't work for me.
```javascript
// {"size":2}
const a = bodybuilder().size(2);

// {"size":2,"from":1}
const b = _.cloneDeep(a).from(1);

console.log(JSON.stringify(a.build()) === JSON.stringify(b.build())); // true
```

**Comment by wa4-fearless-otter** [comment]
You can even try this on your [website](https://bodybuilder.js.org/). Open the browser console and paste this in.
```javascript
const a = bodybuilder().size(2);
const b = Object.assign({}, a).from(1);

console.log(JSON.stringify(a.build()) === JSON.stringify(b.build())); // true
```

**Comment by ferronrsmith** [comment]
It has to do with the body construction. Since clone/deep clone can't recreate an object inside an isolate scope. It wouldn't be possible without a change.

Easiest solution would be to add a method that returns a clone of the inner scope.

**Comment by wa4-fearless-otter** [comment]
I would really appreciate if you could implement this feature.

**Comment by ferronrsmith** [comment]
as @danpaz said it isn't straightforward, because of how bodybuilder object is constructed.

**Comment by wa4-fearless-otter** [comment]
So it's not being implemented?

**Comment by ferronrsmith** [comment]
no

**Comment by johannes-scharlach** [comment]
It's not per se cloning, but one thing I've been doing a lot is
```js
const filterBuilder = bodybuilder()

// add some filters to this filter builder...


// now I need an aggregation with that filter
const builder = bodybuilder()
builder.getFilter = () => filterBuilder.getFilter()
```

afterwards you have two separate instances, both will use the same filter.

I can imagine that we include something like this more deeply in bodybuilder. There are probably 1000 nuances that you may want to see done in a different way, but this is something that may work for your case @wa4-fearless-otter

**Comment by wa4-fearless-otter** [comment]
@johannes-scharlach I already added a clone function with #247

**Comment by johannes-scharlach** [comment]
Thanks, I just noticed. Great job!
