### ISSUE TITLE
[Suggestion] filterIf

### ISSUE THREAD

**Issue by kud** [danpaz/bodybuilder#254]
```javascript
import bodybuilder from "bodybuilder"

const customBodybuilder = (...args) => {
  const bd = bodybuilder(...args)

  bd.filterIf = (cond, ...rest) => {
    if (cond) {
      return bd.filter(...rest)
    }

    return bd
  }

  return bd
}

export default customBodybuilder
```

**Comment by ferronrsmith** [comment]
You can construct this in your own library or code. This isn’t something related to ES and isn’t really necessary for this library

**Comment by ferronrsmith** [comment]
I've added a cookbook label, so if anyone wants a guide on how to extend bodybuilder, this would be useful. Thanks for your contribution.
