### ISSUE TITLE
Support update methods

### ISSUE THREAD

**Issue by vyvital** [danpaz/bodybuilder#257]
Hello,
Are there any future plans to add support of this kind
bodybuilder().script('source', 'ctx._source.field = 'newValue' ')
To build :
```
"script": {
    "source": "ctx._source.field = 'newValue'"
  }
```

**Comment by ferronrsmith** [comment]
Technically you can use **rawOption** to accomplish this.


```javascript
bodybuilder()
    .rawOption('script', {
        "source": "ctx._source.field = 'newValue'"
    })
    .build()
```

Bodybuilder is **an elasticsearch query body builder**

**Comment by KillerAyce** [comment]
Is there any other way to do this, I mean without adding script property.
Are there any plans in neat future to acomplish this?

**Comment by KillerAyce** [comment]
> 
> 
> Is there any other way to do this, I mean without adding script property.
> Are there any plans in neat future to acomplish this?

Nevermind I found a way to achieve this.
`var body =bodybuilder()
.query('match', 'message', 'this is a test')
    .rawOption('_source',  ["id", "primary_client.name.first", "primary_client.name.last","created_date","enrolled_date"]
    )`
