### ISSUE TITLE
Error occurred on nesting with only one query condition

### ISSUE THREAD

**Issue by loriling** [danpaz/bodybuilder#258]
When I use nesting for query, and there is only one query in the nesting, it would be like: 
```
bodybuilder()
        .query('bool', b => b
      		.query('match', 'message', 'this is a test')
   		)
        .build()
```
and the build result is:
```
{
  "query": {
    "bool": {
      "query": {
        "match": {
          "message": "this is a test"
        }
      }
    }
  }
}
```
then it will couse an error: [bool] query does not support [query]

**Comment by ferronrsmith** [comment]
This is a known issue. Nesting a single query doesn’t “roll-up”, which is why it isn’t done. Like any other software bodybuilder has edge case, this is one
