### ISSUE TITLE
Is there a support for elastic field collapsing parameter?

### ISSUE THREAD

**Issue by khobabc** [danpaz/bodybuilder#265]
I have gone through docs but I could not find a method to add field collapsing parameter for following elastic functionality: https://www.elastic.co/guide/en/elasticsearch/reference/6.8/search-request-collapse.html
I only found rawOption parameter. Will this option available be available in future?

**Comment by ferronrsmith** [comment]
Yes the rawOption field will always be available

**Comment by danpaz** [comment]
Similar request and answer as #263. Bodybuilder is focused on the query part of an elasticsearch body. However there is some similar structure in the collapse parameter as in query, so if it's possible to cleanly use the same logic then it may make sense to add it. I'm not able to work on this feature at the moment, though, and rawOption seems like it would work for your use case.
