### ISSUE TITLE
Can you please provide an example for groupby query?

### ISSUE THREAD

**Issue by ankurshah32** [danpaz/bodybuilder#267]
Can we write a query for elastic search by which we can have groupby?
Example: If we have have data of customer like below
```
{
   name : Abc,
   dateReg: 45454545454,( in miliseconds)
   managerName: Xyz,
}
```
Can you please give me an example
how can I get the data group by weekswise and managerName?

**Comment by ferronrsmith** [comment]
```javascript
bodybuilder()
        .aggregation('date_histogram', 'dateReg', {
'calendar_interval' : 'week'
}).aggregation('term', 'managerName')
        .build()
```

It helps to provide a ES query that you need help converting to bodybuilder syntax. i.e. If you don't know what you're doing, bodybuilder can't help you.
