### ISSUE TITLE
Can you please publish 2.2.22 to NPM?

### ISSUE THREAD

**Issue by metallidevils** [danpaz/bodybuilder#276]
I see support for filter aggregations were added to 2.2.22, but NPM still has 2.2.21. Or is there any way to create a filter aggregation in the current version?

**Comment by danpaz** [comment]
It looks like the npm publish step failed on the 2.2.22 commit https://travis-ci.org/github/danpaz/bodybuilder/jobs/653717612. I'll investigate and publish it soon, thanks for flagging!

**Comment by metallidevils** [comment]
Thank you so much!

**Comment by danpaz** [comment]
@metallidevils should be published now. Thanks for your patience!
