### ISSUE TITLE
Escaping hyphens

### ISSUE THREAD

**Issue by nbyrd** [danpaz/bodybuilder#284]
(I am brand-new to elasticsearch so please forgive any incorrect terms below)

I have a search index with documents that all have a "custom_key" field on them. I am trying to write a filter (which is part of a much larger filter) that matches all documents whose custom_key field matches the regular expression `^foo-bar_.*`.

The `orFilter` that I originally wrote for this is like so:
```
courseTypeSubclause.orFilter(
    'wildcard',
    'custom_key',
    'foo-bar_*'
);
```

However, this filter does not work; it is not catching the records whose custom_key values start with "foo-bar_". 

What I discovered is that `-` is documented as a special character in ElasticSearch. So, I tried escaping it (which elasticsearch's official documentation specifies as preceding the character to be escaped with a `\` character).
```
courseTypeSubclause.orFilter(
    'wildcard',
    'custom_key',
    'foo\-bar_*'
);
```

Similarly, that did not work. Neither did the following:
```
courseTypeSubclause.orFilter(
    'wildcard',
    'custom_key',
    'foo\\\-bar_*'
);
```

The following DID work, but considering that the "-bar_" part is missing, this filter does not work for my data set as it is matching records that it should not:
```
courseTypeSubclause.orFilter(
    'wildcard',
    'custom_key',
    'foo*'
);
```

I'm stumped. How do you escape hyphens with this framework? I can't find documentation on this anywhere.

EDIT: Additional things I've tried that did not work:
```
courseTypeSubclause.orFilter(
    'wildcard',
    'custom_key',
    'foo\\-bar_*'
);
```

```
courseTypeSubclause.orFilter(
    'wildcard',
    'custom_key',
    'foo\\\\-bar_*'
);
```

**Comment by nbyrd** [comment]
> I don't think this is something that should be handled by the framework. it's very simple to create a function to do this inside your utilties code
> 
> i.e. The Elasticsearch documentation tells you to **escape special characters before passing it to API**. Basically the same goes for bodybuilder

Please re-read my question. I'm asking how to escape these special characters before passing it to the API and have provided several examples of what I tried which did not work.

**Comment by danpaz** [comment]
@nbyrd note that bodybuilder is just a helper library for building up elasticsearch queries and doesn't modify your inputs in any way. As a first step I'd suggest running your query through the interactive builder on bodybuilder.js.org and verifying that the output is what you expect. Similar issue here in case it's helpful: https://github.com/danpaz/bodybuilder/issues/210. 

I tried searching around and found [this](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html) and [this](https://discuss.elastic.co/t/escaping-special-characters-in-wildcard-query/5819/2) articles which discuss escaping characters (you've no doubt found these too). I noticed they suggest escaping `*` as well, and using double backslash if using JSON for the body. So can you try: `'foo\-bar_\*'` or `'foo\\-bar_\\*'` .
