### ISSUE TITLE
Lodash & treeshaking.

### ISSUE THREAD

**Issue by y-nk** [danpaz/bodybuilder#290]
I can't help but notice:

https://github.com/danpaz/bodybuilder/blob/f2145e15fc5b726cae83e2e02a11f5fd7a12ea08/src/index.js#L1

Would you be open to a PR to refactor this and avoid importing the entire lodash library?

Thanks,

**Comment by danpaz** [comment]
👍  a PR would be great!

**Comment by danpaz** [comment]
Closed by #291
