### ISSUE TITLE
Immutability

### ISSUE THREAD

**Issue by d6u** [danpaz/bodybuilder#3]
Question on future plan. Do you want building query to be immutable:

```js
let query2 = query1.filter(); // create new object
// query2 !== query1
```

or mutable?

```js
let query2 = query1.filter(); // update the same object
// query2 === query1 same object
```

**Comment by danpaz** [comment]
You're right that queries are mutable, but `build` returns a copy
```js
let query2 = query1.filter().build()
// query2 !== query1
```
I think this is common with the Builder pattern, and with `build` returning a copy I'm not too concerned with side effects.

**Comment by d6u** [comment]
Cool, just want to make sure what you want to see in a PR :)

**Comment by danpaz** [comment]
Looking forward to it :smile:
