### ISSUE TITLE
Release new version from master branch

### ISSUE THREAD

**Issue by FatemehOstad** [danpaz/bodybuilder#301]
Hi, 

According to this link https://github.com/advisories/GHSA-p6mc-m468-83gw, versions of lodash prior to 4.17.19 are vulnerable.

Bodybuilder version 2.4.0 is using lodash v4.17.15. I checked the master branch of yours and noticed that you have removed the lodash from there. 

Is it possible for you to publish the new code? 

Bests,
Fatemeh Ostad

**Comment by danpaz** [comment]
Version 2.5.0 has been released 👍 thanks for the heads up!
