### ISSUE TITLE
Dependency lodash.set has Prototype Pollution vulnerability

### ISSUE THREAD

**Issue by MayGo** [danpaz/bodybuilder#303]
https://security.snyk.io/vuln/SNYK-JS-LODASHSET-1320032

I advise replacing that dependency.

**Comment by danpaz** [comment]
> There is no fixed version for lodash.set.

We use lodash.set in several places in the code. Do you have any suggested alternatives by chance?

**Comment by MayGo** [comment]
I just learned about https://www.npmjs.com/package/wild-wild-path, perhaps this has too much functionality.
Or lodash itself and depend on tree shaking to only package used functions.

**Comment by staxie** [comment]
Hi. I opened a pull request for this matter. Please consider checking it out. It's a simple change.
https://github.com/danpaz/bodybuilder/pull/309

**Comment by StefOodle** [comment]
Hello, I also opened a pull request for this issue. #315 . It would be great if you could have a look.

**Comment by remyoudemans** [comment]
Thanks for solving this @StefOodle. Could we get a version with the fix published onto npm please @danpaz?

**Comment by danpaz** [comment]
Yes just published as 2.5.1. This reminded me publishing from Travis CI is still broken https://github.com/danpaz/bodybuilder/issues/297 😞
