### ISSUE TITLE
Delete a filter once it's been added

### ISSUE THREAD

**Issue by elliott-davis** [danpaz/bodybuilder#33]
Is there currently a way to delete a filter from the object once it's been added?

**Comment by danpaz** [comment]
No there's no api to remove a filter currently. Can you show an example of how you'd use that?

**Comment by elliott-davis** [comment]
I think something like

`new Bodybuilder().filter('term','foo','bar').delete()`

Or

```
let foo = new Bodybuilder().filter('term','foo','bar');
foo.filter('term','foo').delete();
```
Right now I have a home rolled version of this but it just uses the generic javascript delete and builds the query when you call build.

**Comment by elliott-davis** [comment]
After looking at the src closer for this repo it might be more feasible to do something like:

```
let foo = new Bodybuilder().filter('term','foo','bar');
foo.delete('filter', 'term', 'foo');
```

**Comment by danpaz** [comment]
Thinking about this a little more, I'm not sure deleting a filter falls within the scope of the project so I'm inclined to punt on this feature. In the interest of keeping the api surface small I think your home rolled solution is the best approach, and I'll close this issue now but happy to continue discussing.
