### ISSUE TITLE
Script Fields on Aggregation

### ISSUE THREAD

**Issue by essajiwa** [danpaz/bodybuilder#34]
Is there currently a way to use `script` properties instead of `fields` on aggregation? like the following example :

` "aggs": {
                "Balance": {
                  "sum": {
                    "script": "doc['DEBIT_DC'].value + doc['CREDIT_DC'].value",
                    "lang": "expression"
                  }
                }
              }`

**Comment by danpaz** [comment]
I believe this is fixed now by https://github.com/danpaz/bodybuilder/pull/55. Try:

```
new Bodybuilder()
        .aggregation('sum', undefined, 'Balance', {
  			script: "doc['DEBIT_DC'].value + doc['CREDIT_DC'].value",
  			lang: 'expression'
		})
        .build()
```

**Comment by essajiwa** [comment]
Great Dan, i'll try this soon. Thanks for your efforts.
