### ISSUE TITLE
Querying nested fields

### ISSUE THREAD

**Issue by DarrylD** [danpaz/bodybuilder#36]
Attempting to do something along the lines of this:
https://www.elastic.co/guide/en/elasticsearch/guide/current/nested-query.html

Got the follow error when attempting to use `nested` as a query type:
`Query type nested not found.`

Any way to query nested fields?

**Comment by gauravarora** [comment]
Looking at the code I could not find a nest query type so the error is correct. I suppose you will need something along the lines of a nested aggregation for queries as well.

**Comment by danpaz** [comment]
There is a `nested` filter type which is probably what you want except for a filter. If so, could duplicate that logic for queries as well.

**Comment by slackbits** [comment]
Nested filters have been [removed in 2.x](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/query-dsl-nested-filter.html).   So the filter would only be appropriate in 1.x.

**Comment by bryanpizzillo** [comment]
I am adding a nested query in for something I am working on and send a pull request when done.

**Comment by parthdesai93** [comment]
I se this  is still open. Do you mind if i send a pull request and try to work on it.

**Comment by danpaz** [comment]
@parthdesai93 sounds great to me!

**Comment by alexcastillo** [comment]
+1

**Comment by danpaz** [comment]
We're trying out a new approach to composing builders, which would also include the ability to write nested queries. Check out the experimental branch #71 if you're interested and to leave any feedback you may have.

**Comment by danpaz** [comment]
The next version of bodybuilder will support `nested` queries, give it a try by installing the beta release:

```
npm install bodybuilder@beta
```

And see [this example](https://github.com/danpaz/bodybuilder/blob/prerelease-bodybuilder-2/test/query-builder.js#L412-L438) for its usage.

If this doesn't solve your issue please reopen!
