### ISSUE TITLE
Is there a GUI based version?

### ISSUE THREAD

**Issue by DaTebe** [danpaz/bodybuilder#37]
Hello!

I'm searching for a GUI based querybuild for elasticsearch 2.x. As far as I can see your tool is the only one that can generate queries for 2.x and is written in JS.

(Edit: I found other libraries that can create es 2.x queries, but your solution seems to be the best. In my opinion)

Is there a GUI based version? If not, what do you think does it take to build a GUI on top of this lib?

Greetings 
Daniel

**Comment by danpaz** [comment]
@DaTebe There is no GUI tool for bodybuilder, but if you're looking for an interactive way to build queries you can try out the command line REPL. Just install the module with `npm install bodybuilder` and then `node node_modules/bodybuilder/repl.js` and you can use bodybuilder just as you would in node. 

```
bodybuilder > var body = new Bodybuilder()
bodybuilder > body.query('match', 'message', 'this is a test').build()
```
