### ISSUE TITLE
Support for pipelined aggregations?

### ISSUE THREAD

**Issue by rimita** [danpaz/bodybuilder#38]
Hi,

This library is really helpful in creating Elasticsearch queries. But in my application, I have many pipelined aggregations like moving average, cumulative sum etc, derivative etc. I haven't come across any doc describing them. Can you please help me with those?

Thanks in Advance

**Comment by danpaz** [comment]
Hi @rimita! I haven't worked with pipeline aggregations but looking at [the docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-pipeline.html) it looks like the syntax for them is predictable and no reason it shouldn't work to write these in the context of bodybuilder. To do that we need to add new definitions for each of the pipeline aggregations, following the pattern from those aggregations already defined in `src/aggregations`.

**Comment by danpaz** [comment]
The next version of bodybuilder will support pipeline aggregations, give it a try by installing the beta release:

```
npm install bodybuilder@beta
```

And see [this example](https://github.com/danpaz/bodybuilder/blob/prerelease-bodybuilder-2/test/aggregation-builder.js#L370-L399) for its usage.

If this doesn't solve your issue please reopen!
