### ISSUE TITLE
Fuzzines - multi_match

### ISSUE THREAD

**Issue by gor181** [danpaz/bodybuilder#40]
Hello!

Nice lib, first of all! 👍  pleasure using it.

Is there support for 

```
GET /my_index/my_type/_search
{
  "query": {
    "multi_match": {
      "fields":  [ "text", "title" ],
      "query":     "SURPRIZE ME!",
      "fuzziness": "AUTO"
    }
  }
}
```

I don't see how I can set `fuzziness` to anything other than `AUTO` (default) as https://github.com/danpaz/bodybuilder/blob/master/src/queries/multi-match-query.js#L9

Doesn't accept the custom object fields.
Maybe we can add a `4th` param called `extra` or similar and just extend the object?

```
export default function multiMatchQuery(fields, query, type='best_fields', extra = {} ) {
  return {
    multi_match: {
      query: query,
      type: type,
      fields: fields,
      ...extra
    }
  }
}
```
I would be happy to submit a PR if this approach seems okay to you.

Thank you,
Goran

**Comment by danpaz** [comment]
That sounds great to me! Happy to look at a PR for it. It may make sense to remove the `type='best_fields` parameter and use the `extra` parameter for all additional options instead.

**Comment by danpaz** [comment]
Looks like this is already addressed in https://github.com/danpaz/bodybuilder/pull/39.

**Comment by gor181** [comment]
Cheers @danpaz
