### ISSUE TITLE
Question regarding nested filters being used outside a `must` clause

### ISSUE THREAD

**Issue by ttacon** [danpaz/bodybuilder#45]
First off, thanks for the great module! Regarding nested filters, it seems as though the default behaviour is to have them all placed underneath a `must` clause? Separately, it seems that to use a bool filter you must provide the fully formed filter itself?

As such, trying to use multiple nested filters inside a `should` clause becomes cumbersome (unless I'm missing something, which I might be). Is there a better way to combine these two in order to get something along the lines of:

```json
{
  "query": {
    "filtered": {
      "filter": {
        "bool": {
          "should": [
            {
              "nested": {
                "path": "$PATH",
                "filter": { "term": {"$TERM": "$VAL_1"} }
              }
            },
            {
              "nested": {
                "path": "$PATH",
                "filter": { "term": {"$TERM": "$VAL_2"} }
              }
            }
          ]
        }
      }
    }
  }
}
```

If not, would you be opposed to exposing some sort of filter builder (to allow creating the nested filter using the builder pattern) to pass constructed filters to the bool filter?

**Comment by danpaz** [comment]
Hey @ttacon, good questions. The default behavior of _all_ filters when using `body.filter` is to place them under a `must` clause. To get `must_not` or `should` filters you should use `notFilter` and `orFilter`, respectively. The bool filter is not really meant to be used directly; when you chain multiple filters together bodybuilder should take care of combining into the expected bool composite filter.

I think this might give you what you wanted:

```
new Bodybuilder()
        .orFilter('nested', '$PATH', 'term', '$TERM', '$VAL1')
        .orFilter('nested', '$PATH', 'term', '$TERM', '$VAL1')
	    .build()
```

I think there's definitely an opportunity to improve documentation around this behavior, so if that interests you I'm happy to look at a documentation PR.

**Comment by ttacon** [comment]
Awesome! Thanks for the suggestion, exactly what I was looking for. When I get a chance I'll definitely submit a documentation PR.
