### ISSUE TITLE
Is there a way to do date range queries or range queries in general?

### ISSUE THREAD

**Issue by cpinto-cb** [danpaz/bodybuilder#48]
Is there support for this in bodybuilder?

https://www.elastic.co/guide/en/elasticsearch/reference/2.3/query-dsl-range-query.html

Ranges on date fields
When running range queries on fields of type date, ranges can be specified using the section called “Date Math”:

{
    "range" : {
        "date" : {
            "gte" : "now-1d/d",
            "lt" :  "now/d"
        }
    }
}

**Comment by danpaz** [comment]
Yes, this:

```
new Bodybuilder()
        .query('range', 'date', {
			"gte" : "now-1d/d",
			"lt" : "now/d"
		})
        .build()
```

would give you:
```
{
  "query": {
    "range": {
      "date": {
        "gte": "now-1d/d",
        "lt": "now/d"
      }
    }
  }
}
```
