### ISSUE TITLE
How to use 'fields'?

### ISSUE THREAD

**Issue by rodrigoalviani** [danpaz/bodybuilder#49]
Its possible to use 'fields' to return only selected fields like [https://www.elastic.co/guide/en/elasticsearch/reference/2.3/search-field-stats.html](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/search-field-stats.html)?

**Comment by danpaz** [comment]
In general the last argument to a query or filter can be an arbitrary object, so that's typically used for advanced settings like `fields`. For example:
```
new Bodybuilder()
        .query('match', 'message', 'this is a test', {fields: 'myfield'})
        .build()

{
  "query": {
    "match": {
      "message": {
        "fields": "myfield",
        "query": "this is a test"
      }
    }
  }
}
```

The caveat is this is not always consistent or available in all queries/filters in bodybuilder, but this is being improved in recent PRs. If this approach doesn't work for you please do open a new issue!

**Comment by rodrigoalviani** [comment]
I'm using filter like this:

`body.filter('term', 'xpto_field', 'xpto_value')`

I tried this:

`body.filter('term', 'xpto_field', 'xpto_value', {fields: ['field1', 'field2']})`

But does not work.
No 'fields' tag was inserted on body after build.

**Comment by danpaz** [comment]
Yup that's one of the filters that does not support additional options (yet; I'm working on a PR, or you are free to submit one too). But looking at the docs for term filter it doesn't look like `fields` is a valid option? https://www.elastic.co/guide/en/elasticsearch/reference/1.4/query-dsl-term-filter.html

**Comment by rodrigoalviani** [comment]
Fields is not a filter option, a filter with fields looks like:
`{
  fields: ['field1', 'field2'],
  filter: {
    term: {
      'xpto_field': 'xpto_value'
    }
  }
}`

**Comment by danpaz** [comment]
Got it, now I think I understand. Please try using `rawOption` to set top level key-value pairs on the request body:
```
new Bodybuilder()
        .rawOption('fields', ['field1', 'field2'])
        .filter('term', 'xpto_field', 'xpto_value')
        .build()
```
