### ISSUE TITLE
Browser build

### ISSUE THREAD

**Issue by danpaz** [danpaz/bodybuilder#5]
Would be great to provide a bundled/minified version of the library for use in the browser.

**Comment by kennyczadzeck** [comment]
I just submitted a pull request with an Angular 1.x build (via Browserify/Uglify)

**Comment by danpaz** [comment]
I just pushed a browser version of the library compiled using webpack, following https://webpack.github.io/docs/library-and-externals.html, you'll find it in the `browser` directory. The library is exported under the name `Bodybuilder` as a UMD module, so you should be able to use it in your angular app.
