### ISSUE TITLE
date_range not supported

### ISSUE THREAD

**Issue by clennpillo** [danpaz/bodybuilder#53]
Is this compatible with the latest version of elasticsearch 2.4.0 ? I've tested with the new aggregation method called date_range but failed.

**Comment by danpaz** [comment]
The date_range aggregation hasn't been added to this lib yet, though you may be able to use a histogram for the same result. Otherwise you're welcome to make a PR to add date_range, it should be fairly straightforward to follow the pattern in src/aggregations -- let me know if I can help!

**Comment by danpaz** [comment]
The next version of bodybuilder will support `date_range` aggregations, give it a try by installing the beta release:

```
npm install bodybuilder@beta
```

And see [this example](https://github.com/danpaz/bodybuilder/blob/prerelease-bodybuilder-2/test/aggregation-builder.js#L276-L299) for its usage.

If this doesn't solve your issue please reopen!
