### ISSUE TITLE
Difference in output in multiline vs single line expression

### ISSUE THREAD

**Issue by vipulbpl** [danpaz/bodybuilder#61]
When I run BodyBuilder using single line expression such as: 
`var body = new BodyBuilder()
.aggregation('terms', "xAxis", 'location_wise')
.aggregation('stats', 'number of schools', 'stats')
.build();`
I get the result like this: 
`{
  "aggregations": {
    "location_wise": {
      "terms": {
        "field": "xAxis"
      }
    },
    "stats": {
      "stats": {
        "field": "number of schools"
      }
    }
  }
}`

But if I use multi line expression like this: 
`var body = new BodyBuilder();
body.aggregation('avg', 'fieldName','location_wise');
body.aggregation('stats','fieldName','stats'); 
body.build();`
I get result like this:
`{
  "_body": {},
  "_filters": {},
  "_queries": {},
  "_aggBuilder": {
    "_aggs": {
      "location_wise": {
        "avg": {
          "field": "fieldName"
        }
      },
      "stats": {
        "stats": {
          "field": "fieldName"
        }
      }
    }
  }
}`
How can I get result like in the first case using multi line expressions to generate the query?

**Comment by danpaz** [comment]
In your second example it looks like you are printing out the value of `body` which is a reference to the in-progress builder. Instead, make a reference to the result of `body.build()` as this returns the built body.

```
var body = new BodyBuilder(); 
body.aggregation('avg', 'fieldName','location_wise'); 
body.aggregation('stats','fieldName','stats'); 
var built = body.build();
// built === { "aggregations": { "location_wise": { "terms": { "field": "xAxis" } }, "stats": { "stats": { "field": "number of schools" } } } }
```
Does that make sense?

**Comment by vipulbpl** [comment]
Yes it does, thanks a lot !

**Comment by miguel-orange** [comment]
@danpaz,
I'm really enjoying this tool! I was about to post the exact same question. Could you add your helpful note above to the readme? May save others time.

**Comment by danpaz** [comment]
@miguel-orange that sounds like a good idea to me. Could you make a PR for it?
