### ISSUE TITLE
Nested aggregation using a loop

### ISSUE THREAD

**Issue by vipulbpl** [danpaz/bodybuilder#62]
Suppose if I have a list of aggregations which I want to nest in an array, how should I go about being able to do that since it expects a parameter for the nested aggregations which means that I'll have to put all the aggregations in the single expression itself and I can't do it by iterating over the loop and inserting the nested aggregations somehow, any other way to achieve this?

**Comment by danpaz** [comment]
Not sure I followed. Can you show me the final desired elasticsearch query you're aiming for?

**Comment by vipulbpl** [comment]
The final query I want to achieve is this : 
`{
  "aggregations": {
    "location_wise": {
      "terms": {
        "field": "xAxis"
      },
      "aggs": {
        "agg_terms_name": {
          "terms": {
            "field": "name"
          },
          "aggs": {
            "agg_terms_class": {
              "terms": {
                "field": "class"
              }
            }
          }
        }
      }
    },
    "stats": {
      "stats": {
        "field": "number of schools"
      }
    }
  }
}`
I know I can achieve this as : 
`var body = new BodyBuilder()
        .aggregation('terms', "xAxis", 'location_wise',null,
        	agg=>agg.aggregation('terms','name',null,null,
        		agg=>agg.aggregation('terms','class')))
        .aggregation('stats', 'number of schools', 'stats')
        .build();`

But if I have the list of aggregations to nested in an array like this: 
`[{
"aggregationType:"terms",
"aggregationField:"name"
},
{
"aggregationType:"terms",
"aggregationField:"class"
}]`

If these were multiple aggregations, I could have simply used multi line expressions and traversed through the array, but I can't do so in case of nested aggregations, any other way to achieve this?

**Comment by danpaz** [comment]
I see, so you'd like to programatically generate arbitrarily nested aggregations from an array of aggregation definitions. Though this is more of a javascript question and not really related to the bodybuilder library, I played around with it a I think something like this will work:

```js

var statements = [{ 
  "aggregationType":"terms", 
  "aggregationField":"name" 
}, { 
  "aggregationType":"terms", 
  "aggregationField":"class" 
}, { 
  "aggregationType":"terms", 
  "aggregationField":"grades" 
}]

new Bodybuilder()
  .aggregation('terms', "xAxis", 'location_wise', null, (agg) => {
    var index = 0;
    var nestedAgg;
    function makeNestedAgg(aggBuilder) {
      if (!statements[index]) return nestedAgg;
      var type = statements[index].aggregationType;
      var field = statements[index].aggregationField;
      index++;
      return aggBuilder.aggregation(type, field, (agg) => makeNestedAgg(nestedAgg = agg));
    }
    return makeNestedAgg(agg);
  }) 
  .aggregation('stats', 'number of schools', 'stats') 
  .build();
```

**Comment by vipulbpl** [comment]
Thanks, that works.
