### ISSUE TITLE
Addition of bucket scripts

### ISSUE THREAD

**Issue by vipulbpl** [danpaz/bodybuilder#63]
I want to include bucket scripts in my query but there doesn't seem to be a way to do that using bodybuilder, the query I want to achieve is something like this: 
`{
    "aggs" : {
        "sales_per_month" : {
            "date_histogram" : {
                "field" : "date",
                "interval" : "month"
            },
            "aggs": {
                "total_sales": {
                    "sum": {
                        "field": "price"
                    }
                },
                "t-shirts": {
                  "filter": {
                    "term": {
                      "type": "t-shirt"
                    }
                  },
                  "aggs": {
                    "sales": {
                      "sum": {
                        "field": "price"
                      }
                    }
                  }
                },
                "t-shirt-percentage": {
                    "bucket_script": {
                        "buckets_path": {
                          "tShirtSales": "t-shirts>sales",
                          "totalSales": "total_sales"
                        },
                        "script": "tShirtSales / totalSales * 100"
                    }
                }
            }
        }
    }
}`
Is there already a way to do so using this library and if not, can you guide me if I want to include it in the library, how should I go about doing the same, will be happy to contribute to the project.
Thanks

**Comment by danpaz** [comment]
You're right that the `bucket_script` aggregation isn't in bodybuilder yet. To add it take a look at the other aggregations in `src/aggregations/` for examples as well as the accompanying unit tests in `test/aggregations/`, and refer to the [elasticsearch docs](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/search-aggregations-pipeline-bucket-script-aggregation.html) for the structure of the query. Looking forward to your PR!

**Comment by danpaz** [comment]
The next version of bodybuilder will support pipeline `bucket_script` aggregations, give it a try by installing the beta release:

```
npm install bodybuilder@beta
```

And see [this example](https://github.com/danpaz/bodybuilder/blob/prerelease-bodybuilder-2/test/aggregation-builder.js#L370-L399) for its usage.

If this doesn't solve your issue please reopen!
