### ISSUE TITLE
Support to Common Queries

### ISSUE THREAD

**Issue by DaniloOliveira28** [danpaz/bodybuilder#69]
Hello,

I am trying to check if bodybuilder supports the  common queries.
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-common-terms-query.html

 If yes, could you show me an example creating a common query?

If not, I could create a PR to bodybuilder support it.

Ty,
Danilo

**Comment by danpaz** [comment]
Hey @DaniloOliveira28 thanks for the issue. I would recommend checking out #68 and see if the approach outlined there would fit your use case and provide any feedback you might have. In the meantime if you need the feature more urgently a PR following the current approach would also be welcome!

**Comment by danpaz** [comment]
The next version of bodybuilder will support `common` queries, give it a try by installing the beta release:

```
npm install bodybuilder@beta
```

And see [this example](https://github.com/danpaz/bodybuilder/blob/prerelease-bodybuilder-2/test/query-builder.js#L108-L124) for its usage.

If this doesn't solve your issue please reopen!
