### ISSUE TITLE
Aggregation

### ISSUE THREAD

**Issue by hongf** [danpaz/bodybuilder#73]
Great tool,
Just wondering is it possible aggregate by Month of a date field?
Thanks
Frank

**Comment by hongf** [comment]
Tried out:
input.push("aggregation('date_histogram', null, 'yourAggregationName', {field: 'reportDate',interval: 'month','time_zone': '+3:00'})");

Query in DSL:
 "yourAggregationName": {
          "date_histogram": {
            "field": "reportDate",
            "interval": "month",
            "time_zone": "+3:00"
          }
        },

**Comment by danpaz** [comment]
Yup I think that's correct

```js
new Bodybuilder()
        .aggregation('date_histogram', null, 'yourAggregationName', {field: 'reportDate',interval: 'month','time_zone': '+3:00'})
        .build()
```

```json
{
  "aggregations": {
    "yourAggregationName": {
      "date_histogram": {
        "field": "reportDate",
        "interval": "month",
        "time_zone": "+3:00"
      }
    }
  }
}
```

You can always test out your syntax in the live editor http://bodybuilder.js.org/
