### ISSUE TITLE
Multiple .query should use 'should' instead of 'must'

### ISSUE THREAD

**Issue by onhate** [danpaz/bodybuilder#76]
Imagine the situation you want to boost the results where title matches but you also want to search for the content of the document with a smaller boost.

This scenario requires multiple match as described here https://www.elastic.co/guide/en/elasticsearch/guide/current/multi-query-strings.html.

Using should the ES will use OR, but using must the document must contain in all matches the search, which is not the case if I only have the match on title.

```
new Bodybuilder()
        .query('match', 'title', { "query": 'super important', boost: 3 })
        .query('match', 'content', { "query": 'super important', boost: 2 })
        .build('v2')
```

```
{
  "query": {
    "bool": {
      "must": [
        {
          "match": {
            "title": {
              "query": "super important",
              "boost": 3
            }
          }
        },
        {
          "match": {
            "content": {
              "query": "super important",
              "boost": 2
            }
          }
        }
      ]
    }
  }
}
```

**Comment by danpaz** [comment]
@onhate you can use .orQuery instead of .query to use the should clause

**Comment by onhate** [comment]
Thanks, I couldn't find it in the documentation. It worked.
