### ISSUE TITLE
Are queries like these possible?

### ISSUE THREAD

**Issue by Kartik-U** [danpaz/bodybuilder#84]
I am looking for nested aggregations which have some more aggregations alongside them.
For example:
`
{  
   "query":{  
      "bool":{  
         "filter":{  
            "range":{  
               "@timestamp":{  
                  "from":1,
                  "to":5
               }
            }
         },
         "should":[  
            {  
               "query_string":{  
                  "query":"*"
               }
            }
         ]
      }
   },
   "aggs":{  
      "time-interval":{  
         "date_histogram":{  
            "field":"@timestamp",
            "interval":"1y"
         },
         "aggs":{  
            "Terms-Agg-0":{  
               "terms":{  
                  "field":"topLvlField",
                  "size":10
               },
               "aggs":{  
                  "Extended-Stat-Agg":{  
                     "extended_stats":{  
                        "field":"units"
                     }
                  },
                  "Terms-Agg-1":{  
                     "terms":{  
                        "field":"nestedAggField",
                        "size":10
                     },
                     "aggs":{  
                        "Extended-Stat-Agg":{  
                           "extended_stats":{  
                              "field":"units"
                           }
                        }
                     }
                  }
               }
            }
         }
      }
   }
}
`

The above query has one level of nesting. It also asks for extended stats on a field, at both levels.
I am able to nest, but not able to add extended stats. Does this require an enhancement, or am i missing something in the syntax?

**Comment by danpaz** [comment]
You can nest any number of aggregations arbitrarily:

```js
new Bodybuilder()
		.orQuery('query_string', 'query', '*')
		.filter('range', '@timestamp', { "from":1, "to":5 })
        .aggregation('date_histogram', '@timestamp', {interval: '1y'}, 'time-interval', (a) => {
  			return a.aggregation('terms', 'topLvlField', {size: 10}, 'Terms-Agg-0', (a) => {
            	return a.aggregation('extended_stats', 'units', 'Extended-Stat-Agg')
                	.aggregation('terms', 'topLvlField', {size: 10}, 'Terms-Agg-1', (a) => {
                  return a.aggregation('extended_stats', 'units', 'Extended-Stat-Agg')
                })
            })
		})
        .build('v2')
```

results in 
```json
{
  "query": {
    "bool": {
      "filter": {
        "range": {
          "@timestamp": {
            "from": 1,
            "to": 5
          }
        }
      },
      "should": [
        {
          "query_string": {
            "query": "query"
          }
        }
      ]
    }
  },
  "aggs": {
    "time-interval": {
      "date_histogram": {
        "field": "@timestamp",
        "interval": "1y"
      },
      "aggs": {
        "Terms-Agg-0": {
          "terms": {
            "field": "topLvlField",
            "size": 10
          },
          "aggs": {
            "Extended-Stat-Agg": {
              "extended_stats": {
                "field": "units"
              }
            },
            "Terms-Agg-1": {
              "terms": {
                "field": "topLvlField",
                "size": 10
              },
              "aggs": {
                "Extended-Stat-Agg": {
                  "extended_stats": {
                    "field": "units"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```
