### ISSUE TITLE
Filters aggregation

### ISSUE THREAD

**Issue by elliott-davis** [danpaz/bodybuilder#90]
I see the ability to do filter aggregations but I can't seem to figure out how to do filters aggregations. An example from the docs is here: https://www.elastic.co/guide/en/elasticsearch/reference/2.4/search-aggregations-bucket-filters-aggregation.html

I just wanted to make sure there was no way to do it currently before I tried to add the functionality.

**Comment by danpaz** [comment]
You're right, but I think the implementation should be very similar for `filters` aggregations. Thanks!

**Comment by elliott-davis** [comment]
I think I actually found a way to make it work. You can just append multiple aggregations for filter and it works the exact same way.

**Comment by jesse1983** [comment]
Do you have a example?

**Comment by ferronrsmith** [comment]
```javascript
bodybuilder().aggregation('filters', {
    "filters": {
        "errors": { "term": { "body": "error" } },
        "warnings": { "term": { "body": "warning" } }
    }
}, 'messages', agg =>
    agg.aggregation('histogram', {
        "field": "timestamp",
        "interval": "1M"
    }, 'monthly')).build();
```
==>

```json
{
  "aggs" : {
    "messages" : {
      "filters" : {
        "filters" : {
          "errors" :   { "term" : { "body" : "error"   }},
          "warnings" : { "term" : { "body" : "warning" }}
        }
      },
      "aggs" : {
        "monthly" : {
          "histogram" : {
            "field" : "timestamp",
            "interval" : "1M"
          }
        }
      }
    }
  }
}
```
