### ISSUE TITLE
Support for Scripted Metric aggregation

### ISSUE THREAD

**Issue by avelis** [danpaz/bodybuilder#95]
Thanks for making this library. I am interested in using this library but noticed no support for the scripted_metric aggregation. Looking at the [docs](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/search-aggregations-metrics-scripted-metric-aggregation.html) I can see also fitting into this framework along with any other aggregation.

I don't mind attempting a PR but there is a challenge in the required parameters for this aggregation (open to suggestions).

**Comment by danpaz** [comment]
Closed by #96
