### ISSUE TITLE
nesting boolean queries

### ISSUE THREAD

**Issue by brumer** [danpaz/bodybuilder#97]
can something like this 
https://www.elastic.co/guide/en/elasticsearch/guide/current/combining-filters.html#_nesting_boolean_queries 
be done using bodybuilder?

**Comment by danpaz** [comment]
Not yet, but this is coming soon in the next version of bodybuilder. You can track the progress on that here: https://github.com/danpaz/bodybuilder/projects/1 😸

**Comment by raphdg** [comment]
Sorry to bring this up, but isn't this related to #104, which is not implemented in v2.0?
